### ISSUE TITLE
[ASK] get a average or a specific value of results

### ISSUE THREAD

**Issue by ZuoxiYang** [PreferredAI/cornac#257]
### Description

Hi, when I uses to Cornac to obtain results of different model as the example you've provided, how can I get a specific result of MAE of MF? In other words,If I runned a experiment 10 times, How can I get a average values of different models? Thanks for your help.
![image](https://user-images.githubusercontent.com/31724147/66791954-f9c9e800-ef28-11e9-9420-46aa8420e4c0.png)

**Comment by tqtg** [comment]
Please take a look at the documentation of [Experiment](https://cornac.readthedocs.io/en/latest/experiment.html) to see how to get a specific result.

If you want average results of multiple runs, you might consider using [Cross Validation](https://cornac.readthedocs.io/en/latest/eval_methods.html#module-cornac.eval_methods.cross_validation).
