### ISSUE TITLE
[ASK] Help on providing user/item features in BPR

### ISSUE THREAD

**Issue by elogicsal** [PreferredAI/cornac#259]
### Description

Requesting help on how to pass user/item features to BPR. I have several numeric and categorical features regarding the user and item that I would like the model to consider.

**Comment by saghiles** [comment]
Hi, BPR is not designed to incorporate user/item auxiliary features. I would recommend considering one of its extensions, e.g., visual BPR ([VBPR](https://github.com/PreferredAI/cornac/blob/master/examples/vbpr_tradesy.py)). The latter was initially proposed to integrate item visual features, but one can also pass other types of item auxiliary information such as texts, as described in this [tutorial](https://github.com/PreferredAI/cornac/blob/master/tutorials/vbpr_text.ipynb). I am not aware of a BPR extension that can consider both user and item features simultaneously, at least it is not implemented in Cornac. Nevertheless, technically it is possible to extend VBPR to further leverage user features.
