### ISSUE TITLE
[ASK] Save and load a Cornac model

### ISSUE THREAD

**Issue by elogicsal** [PreferredAI/cornac#263]
### Description

I'd like some help on how to save a trained Cornac model and load it for subsequent ratings/rankings. The base recommender class does not appear to have methods to save and load models. How is this achieved in the Cornac framework?

Also if the underlying implementations use Tensorflow it would be useful to save the summaries so we can load and analyze in Tensorboard.

**Comment by tqtg** [comment]
Hi @elogicsal 
We are standardizing the process of saving/loading models in Cornac. At the moment, you can use pickle to serialize/deserialize the model as normal Python objects. It should do the job.

**Comment by elogicsal** [comment]
Thank you @tqtg.
Do you have a rough ETA on when save/load/restore will be added to the framework? Is the team also looking into a standard way to save information for use in Tensorboard?

**Comment by tqtg** [comment]
We're not fulltime working on the project so we can not be sure about the time. It depends on the availability of our contributors. Nonetheless, it would be one of the main features of the next couple of releases.

For the logging information with Tensorboard, it would be a nice feature to have though it's not our main focus at the moment.

**Comment by elogicsal** [comment]
@tqtg - Totally understand! Thanks to the team for this well documented framework and the availability of so many models.
