### ISSUE TITLE
[BUG] Dataset object has no attribute 'total_users'

### ISSUE THREAD

**Issue by govorec** [PreferredAI/cornac#299]
### Description
Fitting BPR model throws an error about missing `total_users` attribute in Dataset object.

**Comment by tqtg** [comment]
Hi @govorec 

Please provide more information on:
- the version of Cornac that you are using
- how you install the library (i.e., from which channel)
- which platform/OS that you are running your code

**Comment by tqtg** [comment]
> ### Description
> Fitting BPR model throws an error about missing `total_users` attribute in Dataset object.

We suspect that you construct `Dataset` object manually and fit the BPR model without going through any evaluation method. If that is the case, please reinstall the new Cornac version `1.3.1`. It will fix the issue. Thanks.
