### ISSUE TITLE
[ASK] How to display an exact recommendation result for a user?

### ISSUE THREAD

**Issue by Ravenclawoo** [PreferredAI/cornac#321]
### Description
Hello, may I ask how can I display the recommendation result for a user? Like, if I set a top-10 recommendation, and I want to display what 10 items are recommended for user[0], how should I achieve this?

Best.

**Comment by tqtg** [comment]
Hi @Ravenclawoo 

To get top-k items (e.g., k=10) for a particular user (e.g., user 0) given a trained model, you can call the [`rank()`](https://cornac.readthedocs.io/en/latest/models.html#cornac.models.recommender.Recommender.rank) function of the model as follow:
```python
item_rank = model.rank(user_idx=0)[0]
top_10 = item_rank[:10]
```

Noted that the `rank()` function deals with `user index` and `item index`, mapping from original `user id` and `item id` to the corresponding `user index` and `item index` can be obtained from `model.train_set.uid_map` and `model.train_set.iid_map` respectively (`model.train_set` is an instance of the [Dataset](https://cornac.readthedocs.io/en/latest/data.html#cornac.data.dataset.Dataset) object).

**Comment by Ravenclawoo** [comment]
Thanks so much @tqtg . I am new in this area, I will have a try. Have a good day.

**Comment by Ravenclawoo** [comment]
Forgive me Quoc-Tuan @tqtg , I am really not proficient in this. Let's say if I used my own dataset, and I have already got the "train_data" and "test_data", and I achieved the top-10 recommendation output by following your instruction. But I still do not know how to **map the user and item index back into the id**, would you mind specifying that for me more clearly in my example shown in the screenshot I attached below?

Really appreciate.

<img width="822" alt="截屏2020-04-01 13 06 25" src="https://user-images.githubusercontent.com/33157137/78165628-9b7ebc00-7419-11ea-82b7-1f56cb2b5d6b.png">

**Comment by tqtg** [comment]
@Ravenclawoo for mapping from `user index` back to `user id` (e.g., get id of user with index 0)
```python 
list(model.train_set.user_ids)[0]
```
similarly, from `item index` to `item id` (e.g., get id of item with index 2)
```python 
list(model.train_set.item_ids)[2]
```

**Comment by Ravenclawoo** [comment]
@tqtg Thanks for your patience, it works fine. Have a great day!
