### ISSUE TITLE
[ASK] What's the difference between MF implementation in Cornac with Spotlight?

### ISSUE THREAD

**Issue by amirj** [PreferredAI/cornac#322]
### Description
Thanks for this amazing tool!
There are different MF models in Cornac including [MF](https://github.com/PreferredAI/cornac/tree/master/cornac/models/mf), [NMF](https://github.com/PreferredAI/cornac/tree/master/cornac/models/nmf), [PMF](https://github.com/PreferredAI/cornac/tree/master/cornac/models/pmf), [WMF](https://github.com/PreferredAI/cornac/tree/master/cornac/models/wmf). 
Which one is the most similar to [Spotlight Explicit model](https://github.com/maciejkula/spotlight/blob/master/spotlight/factorization/explicit.py)?
With the same dataset, the obtained results from Spotlight Explicit model is not comparable with Cornac MF models, i.e. based on the Spotlight's implementation MF model is similar to the popularity baseline but based on Cornac's implementation MF model's performance is much lower than the popularity baseline.
Would you please help me to better understand what's the difference?

**Comment by saghiles** [comment]
Hi,

Thanks for you interest in Cornac.

While checking Spotlight Explicit model. Could please share with us the code to reproduce your experiment, and let us know the following.

 - Which dataset are using.
 - Which evaluation metric are you considering. 
 - Do you use the same seed (for Cornac and Spotlight) when initializing the models and splitting the data into training/testing.
- Which loss are you using in spotlight for the explicit model.

**Comment by amirj** [comment]
Thanks for your reply.
- I'm using [Yahoo music](https://webscope.sandbox.yahoo.com/catalog.php?datatype=r&guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAHOctW8eFXHmJkaWi5uibAdRK7_Mf-5j0rqYRJbdtLA_8UqvG7jXDQJ6ULdCSCg21pwZZ5iu7bYk3IZgyHMFWZMKS2MhRgyD2KiFRidOcLoaoYlK2STe30jJR0c6l2vxxTR4o_O4OEmmPuv0kR75xlyZd5lXCLFNxjmJRYU0AJtg). it's a rating dataset very similar to MovieLens.
- I'm using nDCG@20 as the evaluation metric.
- No I don't use the same seed but it's not plausible that random seed makes such a big difference.
- I'm using [the default loss function](https://github.com/maciejkula/spotlight/blob/master/spotlight/factorization/explicit.py#L69) in Spotlight ([regression](https://github.com/maciejkula/spotlight/blob/master/spotlight/losses.py#L169)).

Thanks again.

**Comment by saghiles** [comment]
Welcome, thanks for these information. 

What are the nDCG values you obtain for the different models and implementations?

Could you please check RMSE or MAE as well? I suspect that under the spotlight setting unobserved ratings are treated as zeros, while in MF models missing ratings are ignored. If that is the case, then the MAE/RMSE for the explicit spotlight model should be higher than Cornac MF models.

Often Gaussian MF models that ignore missing ratings and do not rely on negative sampling, perform worst than simple popularity baselines in terms of ranking metrics. For reference please check Figure 3 in this [paper](http://www.cs.columbia.edu/~blei/papers/ChaneyBleiEliassi-Rad2015.pdf), where PMF stands far behind the popularity baseline in several cases.

Please let us know. Thank you!
