### ISSUE TITLE
[ASK]The NDCG value seems a bit strange

### ISSUE THREAD

**Issue by Hbenmazi** [PreferredAI/cornac#324]
### Description

Hi，
- Why are the NDCG values calculated by cornac.metrics.NDCG mostly at [0.01,0.1], while the results calculated by many recommendation system papers are mostly at [0.1,1]?
- Are the two methods of calculating NDCG different? 
- What should I do if I want to reproduce the results of the paper?

BTW, cornac is awesome!

**Comment by saghiles** [comment]
Hi,

Thanks for your interest in Cornac.

Actually Cornac NDCG values are also expected to lie in [0,1]. 
Could you please provide us more information? Which algorithm, dataset and implementation are you focusing on?

In addition, could you please check the answer to issue #323 and let us know whether it helps.

Thanks!

**Comment by Hbenmazi** [comment]
> Hi,
> 
> Thanks for your interest in Cornac.
> 
> Actually Cornac NDCG values are also expected to lie in [0,1].
> Could you please provide us more information? Which algorithm, dataset and implementation are you focusing on?
> 
> In addition, could you please check the answer to issue #323 and let us know whether it helps.
> 
> Thanks!

Algorithm: SoRec(k=8)
Dataset: filmtrust

        My local experiment results are：NDCG@2(0.0557) | NDCG@4(0.0647 ) | NDCG@6(0.0698) | NDCG@8(0.0791 ) . Actually, NDCG is not calculated in the SoRec paper, but [1] choose it (called CFSR in [1]) as comparative method and show that  SoRec's NDCG on filmtrust is about 0.3 to 0.5.
![image](https://user-images.githubusercontent.com/33388552/79724502-3e8c6c80-831a-11ea-98d4-062ff17b9d01.png)

        I also checked the answer to issue [#323](https://github.com/PreferredAI/cornac/issues/323), but I can't find the  the evaluation protocols similar to NCF in [1]. Is this a default setting in academic papers?

[1]:AAAI 2019 Discrete social recommendation

**Comment by saghiles** [comment]
Thanks for providing these details. 

An NDCG@8 of 0.4 on FilmTrust, for an 80-20 (train-test) splitting, seems quite high for SoRec. Some time ago, the NDCG (@ all items) I obtained with the LibRec implementation (using SGD with momentum for optimization) of SoRec was around 0.18 (Table 2 in this [paper](https://saghiles.github.io/papers/socialVMF.pdf)), suggesting that NDCG@8 can be much lower.  

BTW Cornac uses the NDCG variant with a binary relevance value (see this [article](https://en.wikipedia.org/wiki/Discounted_cumulative_gain)), which is the most widely used version in the recommender system community.  

Do you have access to the code of [1]?

**Comment by Hbenmazi** [comment]
[source code of DSR](https://github.com/3140102441/Discrete-Social-Recommendation)
However,  there is only the implementation of the model, but no ndcg.

**Comment by saghiles** [comment]
I see, how about SoRec (CFSR), do you know which implementation they use?

**Comment by Hbenmazi** [comment]
I have no idea.

**Comment by saghiles** [comment]
In this case perhaps the best thing to do is to ask the authors of [1].

**Comment by Hbenmazi** [comment]
Thanks.

**Comment by Hbenmazi** [comment]
> In this case perhaps the best thing to do is to ask the authors of [1].

I asked the author and the NDCG score is calculated on all rated items of a user.

**Comment by saghiles** [comment]
Good to know, thanks for sharing. However, I am afraid that without having access to the code of [1] to reproduce the experiments for SoRec, it may be difficult to explain the discrepancy between Cornac results and [1].
