### ISSUE TITLE
How to use parallel technology to accelerate when searching for hyperparameters？[ASK]

### ISSUE THREAD

**Issue by Hbenmazi** [PreferredAI/cornac#326]
### Description

Just like the n_jobs parameter of [grid search](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) in sklearn.

**Comment by saghiles** [comment]
Parallel computation is not yet available for the hyperparameter search.
