### ISSUE TITLE
[ASK] When a user rates an item multiple times, how can I merge them into one rating by averaging the duplicate rating scores.

### ISSUE THREAD

**Issue by Hbenmazi** [PreferredAI/cornac#327]
### Description

When a user rates an item multiple times, how can I merge them into one rating by averaging the duplicate rating scores.

**Comment by tqtg** [comment]
If your data contains one user rating one item multiple times, only the first observation (encountered during data reading) will be taken into account. The rest will be considered as duplicates.
If you want to merge them into one rating, you should do that little preprocessing before loading data into Cornac.
