### ISSUE TITLE
[ASK] Using early stopping

### ISSUE THREAD

**Issue by YahyaL** [PreferredAI/cornac#328]
### Description
I am comparing different model performance and I am wondering how to implement early stopping for all the models ?

Can you give an example on how to use it, in particular with the Experiment class ?

I have seen that early stop is implemented in MF model but not for other models.

Thank you for this framework.

**Comment by tqtg** [comment]
Hi @YahyaL 

Early stopping is model-dependent and not a standard approach for all models to follow. That said it's up to the author's implementation of the models to support early stopping or not. Even though, Cornac has suitable design and utilities to support that purpose.
If you need early stopping for some of the models and they're not yet supported, feel free to create a PR. We're always welcome contributions. 

Cheers!

**Comment by YahyaL** [comment]
I wanted to use early stopping with VAECF and CTR models.

I have seen the source code for both models and it's straighforward to modify it to implement early stopping. I was hoping that it will be implemented by default in cornac for all models. I was just confused because the Recommender class, inherited by all models, have a function early stopping. I read the code in detail and understood that it was not actually implemented.

Thank you again for this framework. I love how it is designed and easy to use.
