### ISSUE TITLE
[ASK]Customize the output format

### ISSUE THREAD

**Issue by hygeng** [PreferredAI/cornac#342]
### Description

Hi, I would ask a minor question regarding the experiment output. Since I'm taking the accuracy of 6 decimal places, while the default accuracy is 4 places, is there any approach that I could support the new accuracy?

**Comment by tqtg** [comment]
You can retrieve complete numbers from [experiment results](https://cornac.readthedocs.io/en/latest/experiment.html#cornac.experiment.experiment.Experiment.result).

**Comment by hygeng** [comment]
> You can retrieve complete numbers from [experiment result](https://cornac.readthedocs.io/en/latest/experiment.html#cornac.experiment.experiment.Experiment.result).

Thanks! That would address my issue.
Code for reference:
```
experi = cornac.Experiment(
  eval_method=rs,
  models=[ bpr],
  metrics=[mae, rmse, prec, recall, ndcg],
  user_based=True
)
results = experi.result[0].metric_user_results
hr = list(results['Precision@10'].values())
ndcg = list(results['NDCG@10'].values())
recall = list(results['Recall@10'].values())
```
