### ISSUE TITLE
[ASK] Sampling truly negative samples in implicit methods

### ISSUE THREAD

**Issue by yuxinchenNU** [PreferredAI/cornac#347]
Hi,

Thanks for this great package. I was wondering in the case where I have negative feedback (dislikes), how would I tweak the sampling to make sure the truly negative samples are selected? 

Any of your suggestions would be greatly appreciated!

**Comment by tqtg** [comment]
You can tweak this [`uij_iter`](https://github.com/PreferredAI/cornac/blob/97b2efc1b6a9f1da2c3e2080917beae243beb6ea/cornac/data/dataset.py#L512) for your desired negative sampling strategy.

A quick fix could be assigning negative feedback in your data with a negative value (e.g., -1).  That would give you the preference order of `positive` > `unobserved` > `negative`.

**Comment by yuxinchenNU** [comment]
Thanks for your response! I will check uij_iter and the model I am using is BPR.

Just to confirm, for BPR or other methods based on implicit feedback implemented in Cornac, it would take +1, -1, unknown and order the preference as you mentioned? It would be a great and unique capability. Thank you!

**Comment by tqtg** [comment]
Unfortunately, BPR implementation is not using `uij_iter` for negative sampling, thus, the logic discussed above is not applied.  If you want to do so, one solution is to create a BPR model based on VPBR implementation by removing the visual features. That could work as VBPR is using the `uij_iter`.

**Comment by yuxinchenNU** [comment]
@tqtg  Okay. Thanks for your response!
