### ISSUE TITLE
[SUGGESTION] Loade model with save file path doesn't have train_set

### ISSUE THREAD

**Issue by cockroach54** [PreferredAI/cornac#351]
### Description
Hi there
First, thanks for Cornac source code 

When I load model, the absence of model's train_set make mdoel.score(), model.rank() not work at some algorithm like 'MF', 'BPR' ... ect.

this situation raise because of [additional item index confirmation](https://github.com/PreferredAI/cornac/blob/master/cornac/models/mf/recom_mf.pyx)
```
def score():
 ......
 ......
        unk_user = self.train_set.is_unk_user(user_idx)
```

but when use loaded model, many times original train dataset not exist.
It makes model save/load function uselss , or user must have big original dataset.

### Expected behavior with the suggested feature
Model's u_factors and i_factor already have UID and IID
If  `unk_user = self.train_set.is_unk_user(user_idx)` this code revised with i_factors not train_set, 
loaded model could be used with additional dataset load.

**Comment by tqtg** [comment]
Current save/load functions to support re-running experiments in which `train_set` is supposed to be available.
Having said that, the score function of each model can be updated to handle unknown users/items based on the model design.
