### ISSUE TITLE
[H] How to see per user evaluation result

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#364]
### Description
Thank you for putting up cornac, it is a very useful resource for pushing research.

I just wanted to ask if there is a way to see the **per-user evaluation score** for RS models? Let's assume, we do not want to average over user-obtained NDCGs but we want to compute a PDF on the results. How can we get user-related evaluation scores in order to aggregate the results in a specific manner (beyond simple average)? Thank you for your input.

**Comment by tqtg** [comment]
@yasdel when finish running an experiment, it will return you an `ExperimentResult` which is nothing but a list of [Result](https://cornac.readthedocs.io/en/latest/experiment.html#module-cornac.experiment.result), each one per model. For each of them, you have access to `metric_avg_results` and `metric_user_results ` corresponding to average results and per-user results organized by metrics.

**Comment by yasdel** [comment]
thank you for your prompt response. Any idea how I can access to `metric_avg_results` and `metric_user_results `? I am using a classical call. 

```
cornac.Experiment(
  eval_method=rs,
  models=[mf, pmf, bpr, wbpr, userknn, itemknn],
  metrics=[mae, rmse, recall, ndcg, auc, mAP],
  user_based=True
).run()
```

**Comment by tqtg** [comment]
```python
exp_result = cornac.Experiment(
  eval_method=rs,
  models=[mf, pmf, bpr, wbpr, userknn, itemknn],
  metrics=[mae, rmse, recall, ndcg, auc, mAP],
  user_based=True
).run()
```

`exp_result` is an `ExperimentResult` that I mentioned above.

**Comment by yasdel** [comment]
Thank you for your clarification. I don't know if I am missing something, `exp_result` seems to be an object, not a list. How can I have access to `metric_user_results`?

**Comment by tqtg** [comment]
```python
exp_result = cornac.Experiment(
  eval_method=rs,
  models=[mf, pmf, bpr, wbpr, userknn, itemknn],
  metrics=[mae, rmse, recall, ndcg, auc, mAP],
  user_based=True
).run()

for r in exp_result:
  print(r.model_name)
  user_results = r.metric_user_results # <- this is a dictionary
```

That piece of code will help you to access the `metric_user_results` for each of the models in your experiment.

**Comment by yasdel** [comment]
Thanks for the pointer, it looks interesting. However, by running it, I receive your suggestion: `TypeError: 'NoneType' object is not iterable`. Looking at the variable explore, I see the `exp_result` has a type `NoneType` and Value of` NonType object`.

**Comment by tqtg** [comment]
Sorry for the wrong example. I've corrected it.

**Comment by yasdel** [comment]
thanks all look good, I think I have what I needed, thanks for your great support"
