### ISSUE TITLE
[ASK] How to use user defined metadata features associated with a dataset

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#366]
### Description
Is there any way to import user features of dataset in cornac? Let's say given the ml100K dataset, we want to split the dataset into two based on user metadata (e.g., user gender). How is this achieved in cornac?

**Comment by tqtg** [comment]
This tutorial might give you some ideas on how to work with your metadata:
https://github.com/PreferredAI/cornac/blob/master/tutorials/working_with_auxiliary_data.md

**Comment by yasdel** [comment]
ok, great resource, but it turns that user metadata could not be loaded as a built-in option for ML for example. `load_plot()` and `load_feedback() `seem to be the supported info?

**Comment by saghiles** [comment]
Hi, 

The kind of operations you are describing, i.e., splitting ml100k based on metadata is currently not supported in Cornac. I would recommend performing such operation as a preprocessing step, and then feeding the resulting subsets to Cornac, for instance, using the [BaseMethod.from_splits](https://github.com/PreferredAI/cornac/blob/master/examples/given_data.py) function.
