### ISSUE TITLE
[ASK] How to use BPR with given item-item similarities

### ISSUE THREAD

**Issue by wahyudierwin** [PreferredAI/cornac#368]
### Description
Hi,

I have already computed item-item similarities, but how can I utilize it into a BPR model? Probably this is different from `FeatureModality` implemented in the repository.

**Comment by saghiles** [comment]
Hi,

BPR does not integrate any auxiliary data. It only works with user-item interactions. If you are interested in leveraging item-to-item information you can consider using [VBPR](https://github.com/PreferredAI/cornac/blob/master/tutorials/vbpr_text.ipynb) with item-item graph data. Besides BPR, you can consider for instance  [C2PF](https://github.com/PreferredAI/cornac/blob/master/examples/c2pf_example.py) or [MCF](https://github.com/PreferredAI/cornac/blob/master/examples/mcf_office.py), which integrate item-item information.

**Comment by wahyudierwin** [comment]
Thanks for the answer @saghiles . For C2PF and MCF, can we just use computed item-item similarities, instead of providing raw features?

**Comment by saghiles** [comment]
Not sure what do you mean by "raw", but you need to provide a graph of items. Please refer to this [example](https://github.com/PreferredAI/cornac/blob/master/examples/c2pf_example.py) or the datasets [readme](https://github.com/PreferredAI/cornac/blob/master/cornac/datasets/README.md#datasets) for the right graph format and how to feed this information to a model using the ```GraphModality```.

**Comment by wahyudierwin** [comment]
Okay, I will surely read the example. Thanks!
