### ISSUE TITLE
[ASK] About Image-based datasets

### ISSUE THREAD

**Issue by SantiagoEG** [PreferredAI/cornac#370]
### Description
Hello, first of all I would like to thank you the important work in developing this framework. 
I am researching on Image-based recommendation, and my first step with your tool was to load amazon_clothing. 
I am noticing that when I call load_image(), the returned data is not image information. Instead, the obtained data seems to be latent factors (4096 columns per product) extracted from some deep model. This fact also happens for tradesy dataset. 

I would like to confirm that I am right regarding this concern.

**Comment by saghiles** [comment]
Hi,
 
Yes correct the datasets you mentioned come with pretrained image features. We will consider renaming the load_image() function accordingly. If you are interested in the images please refer to the "source" link in the datasets [description](https://github.com/PreferredAI/cornac/blob/master/cornac/datasets/README.md#datasets).

 Thanks for the feedback.

**Comment by saghiles** [comment]
We have renamed the load_image() function as load_visual_feature(). We will release a new version of Cornac soon, and in the mean time, you can re-install Cornac from the source code to take into account these changes.
