### ISSUE TITLE
[BUG] AttributeError: module 'cornac.datasets' has no attribute 'filmtrust'

### ISSUE THREAD

**Issue by Maeril** [PreferredAI/cornac#387]
### Description

Hi again, really sorry to open up another ticket so soon after, but Cornac doesn't recognize Filmtrust as an existing dataset. 

When executing:
`ds = cornac.datasets.filmtrust.load_feedback()`

I get the following error:
`AttributeError: module 'cornac.datasets' has no attribute 'filmtrust'`

Filmtrust **seems to be absent from the datasets' init file** (on the other hand, for instance, netflix and movielens are present). 

Could you please fix this ? Thank you very much in advance. :)

### In which platform does it happen?

OS:
Ubuntu 20.04

Packages:
Python 3.6.4
Tensorflow 1.15
Cython 0.29.21
PyTorch 1.4

### How do we replicate the issue?

Run `first_example.py` but replace movielens by filmtrust.

### Expected behavior (i.e. solution)

The experiment should run successfully and output the results. 

### Other Comments

**Comment by tqtg** [comment]
@Maeril Thanks for spotting this issue. We've released a new version ([v1.11.0](https://github.com/PreferredAI/cornac/releases/tag/v1.11.0)) to fix that.

**Comment by Maeril** [comment]
Thank you for the fix and for your reactivity @tqtg :) 

I have tried updating through conda and pip3, but they don't seem to find that latest version. 
Do I have to update directly from the git source ?

**Comment by tqtg** [comment]
```sh
pip3 install --upgrade cornac
```
It should be able to get you the latest version.

**Comment by Maeril** [comment]
Thanks ! It works now. Have a great day :)
