### ISSUE TITLE
[BUG] "ValueError: could not convert string to float: 'e' " on train_data devoid of any alphabetical characters 

### ISSUE THREAD

**Issue by Maeril** [PreferredAI/cornac#389]
### Description

Good day, it is me again. 

I have been attempting to build a `BaseMethod()` object using "train_data" and "test_data" I split myself, so that I may then include it in an experiment. 
Both "train_data" and "test_data" dataframes are in the "UIR" format, and contain exclusively numerical values in all the columns.

To build said `BaseMethod()` object, I am using the class method from_splits() and providing my train/test dataframes.

Despite my best attempts, I keep getting the same error: "_ValueError: could not convert string to float: 'e'_ "

I have tried: 
- Looking for rows containing 'e' (there are none, dataset is clean - I use the base Filmtrust dataset provided in Cornac and only perform the split myself),
- Converting ratings column to float beforehand, even though I couldn't locate any faulty cell,
- Switching from class method `from_splits()` to `build()` in an attempt to emulate the end of the `RatioSplit()` class, but the same error appears.

Thank you very much in advance for any help or advice you could provide.

Mae

### In which platform does it happen?

Ubuntu 20.04.1 LTS

### How do we replicate the issue?

1) Load `~/.cornac/filmtrust/ratings.txt` with pandas' read_csv.

2) Split train & test data using this function:

`def improved_split_train_test(df, ratio=0.8, timestamp=None, user_id=None):`	

	# If no timestamp or no user_id, do a classic random split
	if timestamp is None or user_id is None:
	 	df['_is_train'] = np.random.uniform(0,1,len(df)) <= ratio
	else:
		# Sort timestamps in ascending order then group by user_id
		df.sort_values([timestamp, ], ascending=True, inplace=True)
		grouped_df = df.groupby([user_id, ])
		# Compute rank over timestamp by user_id groups
		df_rank = grouped_df[timestamp].rank()
		# Compute size of user_id groups...
		df_size = grouped_df.size().to_frame('_size')
		# Add _rank and _size columns to the original dataframe
		df['_rank'] = df_rank
		df = df.join(df_size, on=user_id, how='left')
		# Select train is rank <= ratio * size
		df['_is_train'] = df['_rank'] <= ratio * df['_size']
		df.drop(['_rank', '_size',], axis=1, inplace=True)

	# Create train and test depending on _is_train flag
	train = df[df['_is_train']==True].drop(['_is_train',], axis=1).reset_index(drop=True)
	test = df[df['_is_train']==False].drop(['_is_train',], axis=1).reset_index(drop=True)
	return train, test

3) Build split object through `BaseMethod()`  (error will pop through that last line) :
`	split = eval_methods.BaseMethod()`
`	split.from_splits(train_data=train_data, test_data=test_data)`

### Expected behavior (i.e. solution)

The `from_splits()` class method should return a `BaseMethod()` object, ready for inputting in `Experiment()`.

______________________________________

**Edit 1:** I investigated the problem a bit more, and found that when "rating" column has a value of 'e', it comes from `cornac/data/dataset.py , line 357`.

When printing the values at that stage of execution:

    idx = 0
    uid = 'u'
    iid = 's'

So we have: 0, 'u', 's', 'e' ....
It's probably the header: "0 user_id item_id rating" that wasn't properly skipped, and is now treated as actual data.

I don't know where I can indicate to skip that first line though.

______________________________________

**Edit2:** I checked what the values were further down the loop:

    idx = 1
    uid = 'i'
    iid = 't'
    rating = 'e'

then: 

    idx = 2
    uid = 'r'
    iid = 'a'
    rating = 't'
 
Finally, when idx == 3 it shows up empty.

It's as if the dataframe has been pivoted to the side. Really strange !

**Comment by Maeril** [comment]
**Update:** I investigated the problem a bit more, and found that when "rating" column has a value of 'e', it comes from cornac/data/dataset.py, line 357.

When printing the values at that stage of execution:
- idx is 0
- uid is 'u'
- iid is 's'

So we have: 0, 'u', 's', 'e' .... 
It's probably the header: "0  user_id   item_id   rating" that wasn't properly skipped, and is now treated as actual data.

I don't know where I can indicate to skip that first line though.

**Comment by saghiles** [comment]
Hi Mae, 

Thanks for reporting this issue. It looks like you are getting this error because your ratings are not numbers. Have you considered loading and splitting FilmTrust using Cornac code and see if you are still getting the same error? Here is an [example](https://github.com/PreferredAI/cornac/blob/master/examples/sorec_filmtrust.py) on how to do so.

Please let us know if this helps.

**Comment by Maeril** [comment]
Hi,
Thank you for your swift reply. 
You're right, I have found out I'd mixed up my data formats ! 
Apologies and thank you for your time.
Mae
