### ISSUE TITLE
[BUG] saving loading models broken: 'BiVAECF' object has no attribute 'train_set'

### ISSUE THREAD

**Issue by StijnVerdenius** [PreferredAI/cornac#390]
### Description
Saving BiVAECF and then loading same model leads to the following error when running inference: 'BiVAECF' object has no attribute 'train_set'

### In which platform does it happen?
- Ubuntu 18.04.5 LTS
- Python 3.6.9
- Cornac 1.10.0

### How do we replicate the issue?

```
from random import choice, random

from cornac.models import BiVAECF

from cornac.data import Dataset
import os

fake_users = list('abcdefghijklmnop')
fake_items = list('ABC')

fake_data = []
for user in fake_users:
    for item in fake_items:
        score = int(random() > 0.75)
        if score >= 1:
            fake_data.append((user, item, 1))


model1 = BiVAECF(n_epochs=100, verbose=True)

data = Dataset.build(fake_data)

trained_model = model1.fit(train_set=data)
print(trained_model.score(0))
trained_model.save('./testdir')
filename = list(os.listdir('./testdir/BiVAECF'))[0]
loaded_model = BiVAECF.load('./testdir/BiVAECF/'+filename)
print(loaded_model.score(0))
print(loaded_model.score(0) == trained_model.score(0))
```
yields:

```
 line 42, in <module>
    print(loaded_model.score(0))
  File "virtualenvs/recommender/lib/python3.6/site-packages/cornac/models/bivaecf/recom_bivaecf.py", line 213, in score
    if self.train_set.is_unk_user(user_idx):
AttributeError: 'BiVAECF' object has no attribute 'train_set'
```
### Expected behavior (i.e. solution)
1. loading and saving should work for all models (not just BiVAECF)
2. train_set should be accessible in all models (not just BiVAECF). If I load in another model I need the train set to convert item and user ids to its UID indexes and this will be hard to keep consistent if I have to save this myself separately.

**Comment by tqtg** [comment]
Hi @StijnVerdenius,

Thanks for reporting the issue.

Currently, all models in Cornac requires `train_set` to check for known/unknown users and items. We don't save `train_set` object together with the model because it will increases the size of saved model. It's also potentially being duplicate when you have multiple models in one experiment.

Suggested solution: you can save the `train_set` object (e.g., dump using pickle) independently from the model, then later load it back and reassign the `train_set` reference to the loaded model.

**Comment by Ahmed-Abd-El-Samea** [comment]
Hi @tqtg,

Can you please provide more information on how to use your solution?
I'm using the CTR model and tried the following line:
```
 pickle.dump(ctr.train_set, open('train_set.pkl','wb'))
 ```` 
 But got the following error:
 ```
PicklingError                             Traceback (most recent call last)
<ipython-input-44-ab85de2124be> in <module>
----> 1 pickle.dump(ctr.train_set, open('train_set.pkl','wb'))

PicklingError: Can't pickle <function <lambda> at 0x7fe7b543f9d8>: attribute lookup <lambda> on cornac.data.text failed
```
I'm not sure what might be the problem here

**Comment by Ahmed-Abd-El-Samea** [comment]
Well, apparently pickle can't handle lambda functions that are used in the CTR model.
So, the solution was using the [cloudpickle](https://github.com/cloudpipe/cloudpickle) package instead

**Comment by MisterArbazzz** [comment]
hi @Ahmed-Abd-El-Samea , thank you for raising this issue. 

i was able to save the train_set object using pickle, but how to load it back and reassign the train_set reference to the loaded model. 

i am using the [bivaecf](https://cornac.readthedocs.io/en/latest/models.html#module-cornac.models.bivaecf.recom_bivaecf) model

**Comment by nguyenthekhoig7** [comment]
For those who found this issue later, here is a working solution. Following @tqtg (thank you for your suggestion @tqtg ) 
> Suggested solution: you can save the train_set object (e.g., dump using pickle) independently from the model, then later load it back and reassign the train_set reference to the loaded model.


You can save and load `train_set` by using [`cornac.data.Dataset.save`](https://cornac.readthedocs.io/en/latest/api_ref/data.html#cornac.data.dataset.Dataset.save) and [`cornac.data.Dataset.load`](https://cornac.readthedocs.io/en/latest/api_ref/data.html#cornac.data.dataset.Dataset.load).

### Full code
For saving
```
# save model
model_path = model.save(save_dir = 'trained_models')

# compose path for train_set file
model_dir = os.path.dirname(model_path)
model_name = os.path.basename(model_path)
train_set_name = model_name.replace('.pkl','_train_set.pkl')
train_set_path = os.path.join(model_dir, train_set_name)

# save train_set
model.train_set.save(train_set_path)
```

Loading
```
model2 = cornac.models.BiVAECF.load(model_path = model_path)  # change BiVAECF to your model
model2.train_set = cornac.data.Dataset.load(train_set_path)
```
