### ISSUE TITLE
[How to change the optimization of BPR from max number of iteration to a condition]

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#391]
### 
I would like to change the SGD optimization procedure in BPR such that instead of max number of iterations, based on a condition we can stop BPR training. For the condition, I need to check norm of `p_u` and `q_i` and do a comparison on their norm value. Here is part of the code in recom_bpr.pyx I have identified:

```
      with trange(self.max_iter, disable=not self.verbose) as progress:
            for epoch in progress:
                correct, skipped = self._fit_sgd(rng_pos, rng_neg, num_threads,
                                                user_ids, X.indices, neg_item_ids, X.indptr,
                                                self.u_factors, self.i_factors, self.i_biases)
                print(self.i_factors)
                progress.set_postfix({
                    "correct": "%.2f%%" % (100.0 * correct / (len(user_ids) - skipped)),
                    "skipped": "%.2f%%" % (100.0 * skipped / len(user_ids))
                })


```
I put a `print(self.i_factors)` function to check the value of `i_factors`. However, nothing gets printed. 
Could you give me some guidelines on how I can reach my goal based on the code of BPR written by cornac?
Thank you very much.
YAS

**Comment by tqtg** [comment]
Hi @yasdel,

The BPR code is written as a Cython extension and needed to be re-compiled everytime you change something. The command below can trigger the compilation:
```sh
python setup.py build_ext --inplace
```
