### ISSUE TITLE
[ASK] Per-item metrics

### ISSUE THREAD

**Issue by MichaelVSinko** [PreferredAI/cornac#393]
Hello, thanks for this framework and for your work.
**Is there a way to get / calculate per-item metrics (same as metric_user_results but for items)?**

**Comment by tqtg** [comment]
@MichaelVSinko can you elaborate more on what metrics and how you want to compute them for items?

**Comment by MichaelVSinko** [comment]
I don't know, I'm researching now. Maybe there is some solution.
I want to find how well the model makes predictions for a particular item. As a result, I want to get a rating of items from best to worst by predictions accuracy.

For example, I can try to calculate the ratios for the test set:
- number of hits of the item in the top k-items to the total number of users who rated the item >threshold: number_of_hits/number_of_positive_reviews = TPR,
- number of hits of the item in the top k-items to the total number of users who rated the item <threshold: number_of_miss/number_of_negative_reviews = FPR.
- ...

The example above is bad, just for understanding.

**Comment by tqtg** [comment]
What you are describing could be done. It's just that the current evaluation scheme is more user-oriented (including the way test data is organized as well as the implementation of metrics).

You can try to modify the `rating_eval()` and `ranking_eval()` in [cornac/base_method.py](https://github.com/PreferredAI/cornac/blob/master/cornac/eval_methods/base_method.py) based on your need. One feasible solution is exchanging the role between user and item, then you will have the evaluation being item-oriented.

**Comment by MichaelVSinko** [comment]
will trying. Thanks for your answer
