### ISSUE TITLE
request for source of "cornac.models.knn.similarity.compute_similarity"

### ISSUE THREAD

**Issue by poursistani** [PreferredAI/cornac#395]
how can I view  and change the source of "cornac.models.knn.similarity.compute_similarity"

**Comment by tqtg** [comment]
The code is inside `cornac/models/knn/similarity.pyx`. It's a Cython module so you need to re-compile the code every time you make any changes for it to be effective. Further information on Cython could be found [here](https://cython.readthedocs.io/en/latest/src/quickstart/overview.html).
