### ISSUE TITLE
[ASK]Do we have a method to extract the trained embeddings?

### ISSUE THREAD

**Issue by Heepo** [PreferredAI/cornac#409]
### Description

Do we have a method to extract the trained embeddings? I want to use the embeddings to do retrieval in production by using tools like faiss.
Anyway, this project is a neat work, thanks for your contributions!

**Comment by tqtg** [comment]
@Heepo technically you can extract trained weights of any models in Cornac. The code might be different depending on the model implementation. Let me know which model you're dealing with so that I provide some ideas.

**Comment by Heepo** [comment]
> @Heepo technically you can extract trained weights of any models in Cornac. The code might be different depending on the model implementation. Let me know which model you're dealing with so that I provide some ideas.

Thanks for replying! I am trying to apply the BPR FM algorithm. 
And another question arised when I was trying training it with a large implicit feedback dataset(tens of millions). The BPR fit function just caused the program died without any errors or logs. Any ideas?
I also tried pyspark mllib, as it realized the ALS implicit fm method. It can't print any intermediate losses during the training process, the time consuming is driving me crazy...

**Comment by tqtg** [comment]
For BPR, you can obtain learned weights (in the format of NumPy array) via:
```python
bpr_model.u_factors  # user factors
bpr_model.i_factors  # item factors
bpr_model.i_biases  # item biases
```
Those factors are sufficient for making ranking prediction with BPR model. 

For large dataset, I'm not so sure. It could be hardware issue (not sufficient memory), or might be issue in the implementation too. If you can provide the dataset, I might test it out and see what went wrong.

**Comment by Heepo** [comment]
> For BPR, you can obtain learned weights (in the format of NumPy array) via:
> 
> ```python
> bpr_model.u_factors  # user factors
> bpr_model.i_factors  # item factors
> bpr_model.i_biases  # item biases
> ```
> 
> Those factors are sufficient for making ranking prediction with BPR model.
> 
> For large dataset, I'm not so sure. It could be hardware issue (not sufficient memory), or might be issue in the implementation too. If you can provide the dataset, I might test it out and see what went wrong.

Thanks very much! I will try this. I think it is the memory issue.

**Comment by msurya1** [comment]
For the user and item factors, is there an approach for connecting back to their respective user and product IDs that we started with?

**Comment by tqtg** [comment]
@msurya1 you can obtain such user/item id mapping via `model.trainset.uid_map` and `model.trainset.iid_map`

**Comment by msurya1** [comment]
How do we extract the user and item embeddings from the BiVAE model?
