### ISSUE TITLE
[ASK] Multithreading in BiVAE

### ISSUE THREAD

**Issue by ip-iulia** [PreferredAI/cornac#410]
### Description

I have recently started to experiment with the BiVAE model. I noticed that the training of this model appears to be multithreaded when it is trained on CPU only. Could you please advise if there is a way to control or know the number of threads used by the model? Is there a default number of threads or a parameter that controls this? Thank you.

**Comment by saghiles** [comment]
Hi @ip-iulia, the current implementation of BiVAE is itself not Multithreaded, we can therefore not specify the number of threads. However, it is possible that some predefined functions used in BiVAE code are multithreaded, but still currently we do not have control over the number of threads for those functions.

**Comment by tqtg** [comment]
@ip-iulia the implementation of BiVAE uses PyTorch as backend so it's up to PyTorch to obtain best efficiency based on your available resources. Any particular reason why you want to set a specific number of threads?

**Comment by ip-iulia** [comment]
Hi @saghiles, @tqtg, thank you for your replies. I was curious to see if the number of threads could be configured rather than allowing PyTorch to determine it based on the available resources.

**Comment by tqtg** [comment]
@ip-iulia you can use [torch.set_num_threads(int)](https://pytorch.org/docs/stable/generated/torch.set_num_threads.html) API. However, it also depends on what parallelization library being used on your machine and needed to be configured properly. More details can be found [here](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html).
