### ISSUE TITLE
Fit a model using modalities

### ISSUE THREAD

**Issue by miguelangelorebelo** [PreferredAI/cornac#411]
### Fit using modalities
Hello,

First of all, I can't thank you enough for your efforts with Cornac, it is a really powerful tool.
I'm trying to implement PCRL using Cornac. The experiments work as shown in examples. But I can't fit the model. There seems to be a lack of documentation on this area, I can't find how to do it in any page.  Here's the issue:

![imagem](https://user-images.githubusercontent.com/51267254/120991912-fcbac180-c779-11eb-9168-3086c4958fbd.png)

I hope you can help me.

my very best,

Miguel Ângelo Rebelo

**Comment by tqtg** [comment]
Could you provide specific piece of code that causes the errors?

**Comment by saghiles** [comment]
Hi, could you let us know as well if you can run the PCRL [example](https://github.com/PreferredAI/cornac/blob/master/examples/pcrl_example.py)?

**Comment by miguelangelorebelo** [comment]
> 
> 
> Hi, could you please let us know as well if you can run the PCRL [example](https://github.com/PreferredAI/cornac/blob/master/examples/pcrl_example.py)?

Hello! Yes, I can run it perfectly. no issues.

**Comment by miguelangelorebelo** [comment]
> 
> 
> Could you provide specific piece of code that causes the errors?

do you mean this? It's when I try to fit the model. I add the modalities to the data object and then fail trying to fit it. 

![imagem](https://user-images.githubusercontent.com/51267254/121566501-7d491e80-ca15-11eb-8a89-4f73f6df8844.png)

**Comment by tqtg** [comment]
To train the model successfully, it requires item index mapping between rating data and item graph data. It's done via one of the evaluation methods. Thus, if you construct the dataset and graph modality yourself, you need to understand the index building process. 
I would not recommend to do it manually but to provide them into the evaluation method as shown in the example.

**Comment by miguelangelorebelo** [comment]
> 
> 
> To train the model successfully, it requires item index mapping between rating data and item graph data. It's done via one of the evaluation methods. Thus, if you construct the dataset and graph modality yourself, you need to understand the index building process.
> I would not recommend to do it manually but to provide them into the evaluation method as shown in the example.

ok, thank you for the explanation. So, after I evaluate, then I can predict the ratings individually, right?

**Comment by tqtg** [comment]
Definitely!
After the experiment finished, you can grab the trained model and make rating/ranking predictions as expected.

**Comment by miguelangelorebelo** [comment]
Great! I didn't expect that at all. Thank you so much for your kind attention.
