### ISSUE TITLE
[BUG] Unable to install Cornac on local M1 Mac, running miniforge 3

### ISSUE THREAD

**Issue by nhog88** [PreferredAI/cornac#414]
### Description ###

Unable to install Cornac via all 3 methods, conda-forge install, pip install and Cython install for m1 Mac using miniforge 3.
Please refer to the 3 attached text files for the respective logs
[Log for cython install.txt](https://github.com/PreferredAI/cornac/files/6764501/Log.for.cython.install.txt)
[Log for pip install cornac.txt](https://github.com/PreferredAI/cornac/files/6764502/Log.for.pip.install.cornac.txt)
[Log for conda-forge install.txt](https://github.com/PreferredAI/cornac/files/6764503/Log.for.conda-forge.install.txt)

### In which platform does it happen?
M1 Mac running miniforge 3, Conda version 4.10.3

### How do we replicate the issue?
Run: pip install Cornac
Run: conda install 
Run:
pip3 install Cython
git clone https://github.com/PreferredAI/cornac.git
cd cornac
python3 setup.py install

**Comment by tqtg** [comment]
Do you have [brew](https://brew.sh/2020/12/01/homebrew-2.6.0/) installed on your Mac?

If yes, you can try to install a gcc compiler that supports OpenMP by this command:
```sh
brew install gcc | brew link gcc
```
then try to install Cornac using pip:
```sh
pip3 install cornac
```

Hope this solve the issue.

**Comment by nhog88** [comment]
Hi tqtg,

Yes I have brew installed, and the gcc is linked. However pip3 install cornac doesn't work, logs for reference
[Log for Brew gcc and pip3 install.txt](https://github.com/PreferredAI/cornac/files/6764810/Log.for.Brew.gcc.and.pip3.install.txt)

**Comment by tqtg** [comment]
@nhog88 you're using Python 3.9 (as I see in your log). You can try to create an anaconda environment with Python 3.8 and install Cornac from `conda-forge` channel again. I've tested it on my Mac M1 and it works with Python 3.8 (current Cornac builds on Anaconda cover Python 3.6-3.8).
