### ISSUE TITLE
[ASK] Auxiliary data User related

### ISSUE THREAD

**Issue by Rico2000** [PreferredAI/cornac#423]
### Description
Hey, 

I have a question regarding auxiliary data. I have an intergation matrix between about 1 million users and 50 products. Additionally there is a lot of information about each user, which is not related to the interactions. These describe the characteristics of a user in more detail. I have not found a way to use this data. Is there a possibility for this? 

Best regards
Rico

**Comment by saghiles** [comment]
Hi @Rico2000, I would recommend taking a look at this [tutorial](https://github.com/PreferredAI/cornac/blob/master/tutorials/working_with_auxiliary_data.md). Please let us know if it helps.

**Comment by Rico2000** [comment]
Hey @saghiles , 
unfortunately I already know this tutorial. My problem is that I have no graphs or text or images auxiliary data. The auxiliary data in my dataset are tabular and always refer to individual users. So I have additional data for each user that I would like to use.  This data is not related to the interactions, but is described the properties of a user
I have read that this is possible for some processes but have not found a way to do it yet.
 I hope I could describe my problem correctly
Thanks a lot

**Comment by tqtg** [comment]
@Rico2000 for a more general case, you can take a look at [FeatureModality](https://cornac.readthedocs.io/en/latest/data.html#module-cornac.data.modality) which takes in user/item feature vectors as input. This will suit your tabular data better than more specific Text/Image/Graph modality.
Btw, Text/Image/Graph-Modality extends FeatureModality so it should be compatible with most of the models in Cornac.

**Comment by Rico2000** [comment]
Hey,
thanks I have already seen that these extend from FeatureModality. Can I then use this FeatureModality by specifying it in the Evaluation Method at user_feature? 
Is this then used automatically by models that support auxiliary data? 
Thanks a lot

**Comment by tqtg** [comment]
Yes, you can specify `user_feature` and `item_feature` in the evaluation method. However, they will not be automatically consumed by the models. You need to do some modification to the model implementation and it's model-specific. 
For example, you can take [CDL](https://cornac.readthedocs.io/en/latest/models.html#module-cornac.models.cdl.recom_cdl) implementation and turn the denoising autoencoder to encode your user features instead of item text.

**Comment by Rico2000** [comment]
oke thanks. I wil try and see how it works 👍

**Comment by tqtg** [comment]
@Rico2000 just remember that we have an example for BiVAE model taking in user/item features directly. You can take a look @ https://github.com/PreferredAI/bi-vae/blob/main/bivae_cap.py
