### ISSUE TITLE
[ASK] FeatureModality ids 

### ISSUE THREAD

**Issue by Rico2000** [PreferredAI/cornac#424]
Hey,
I want to add user auxiliary data to my data. To do this, I put this data together as FeatureModality. In my data each user has auxiliary data which is always constant and not related to each interaction.
 As I understood the [documentation ](https://cornac.readthedocs.io/en/latest/data.html#module-cornac.data.modality) I have to add the data for each user and the respective id or the row indeices have to match the row indices from the Dataset.
The ids are strings. These match to one or more entries that I have added to the data set in the BaseMethod. 
So what am I doing wrong?

Thanks 
Best regards
Rico

### Code
```python
uf_modality = FeatureModality(
    features  = df_zsa_pre_pd.drop(["nr_kunden"],axis = 1).to_numpy(),
    normalized= False,
    ids  = df_zsa_pre_pd["nr_kunden"]
)
rs = BaseMethod.from_splits(train_pd[["nr_kunden","Produkt","Rating"]].to_numpy(),
                            test_pd[["nr_kunden","Produkt","Rating"]].to_numpy(),
                           user_feature = uf_modality,
                           verbose = 1)
```

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-36-bfa2eb8e28d1> in <module>
      2                             test_pd[["nr_kunden","Produkt","Rating"]].to_numpy(),
      3                            user_feature = uf_modality,
----> 4                            verbose = 1)

/data/share/envs/sdldkr/lib/python3.6/site-packages/cornac/eval_methods/base_method.py in from_splits(cls, train_data, test_data, val_data, fmt, rating_threshold, exclude_unknowns, seed, verbose, **kwargs)
    747 
    748         return method.build(
--> 749             train_data=train_data, test_data=test_data, val_data=val_data
    750         )

/data/share/envs/sdldkr/lib/python3.6/site-packages/cornac/eval_methods/base_method.py in build(self, train_data, test_data, val_data)
    583 
    584         self._build_datasets(train_data, test_data, val_data)
--> 585         self._build_modalities()
    586 
    587         return self

/data/share/envs/sdldkr/lib/python3.6/site-packages/cornac/eval_methods/base_method.py in _build_modalities(self)
    535                 uid_map=self.train_set.uid_map,
    536                 iid_map=self.train_set.iid_map,
--> 537                 dok_matrix=self.train_set.dok_matrix,
    538             )
    539 

/data/share/envs/sdldkr/lib/python3.6/site-packages/cornac/data/modality.py in build(self, id_map, **kwargs)
     96 
     97         if (self.ids is not None) and (id_map is not None):
---> 98             self._swap_feature(id_map)
     99 
    100         if self.normalized:

/data/share/envs/sdldkr/lib/python3.6/site-packages/cornac/data/modality.py in _swap_feature(self, id_map)
     82             if new_idx is None:
     83                 continue
---> 84             assert new_idx < new_feats.shape[0]
     85             new_feats[new_idx] = self.features[old_idx]
     86             new_ids[new_idx] = raw_id

AssertionError: 
```

**Comment by tqtg** [comment]
@Rico2000 two questions:

1. Is `nr_kunden` considered user ID in your dataset?
2. Have you tried to filter the user auxiliary data such that:
  - one `nr_kunden` corresponds to one feature vector?
  - only `nr_kunden` in rating data are provided to `FeatureModality`?

**Comment by Rico2000** [comment]
@tqtg 
1. yes ``nr_kunden`` is considered as ``user ID``
2. Problem solved there was a problem in tge data cleaning and some of the user did not have auxilary data

One last question: 
is there a possibility to change the auxiliary data for the training dataset and test dataset? The auxiliary data changes over time and in ``BaseMethod.fromsplits`` there is only the possibility to specify ``user_feature``. But not to set them explicitly for training and test dataseta and validation set . Thanks a lot

**Comment by tqtg** [comment]
@Rico2000 if the same users, either in training, validation, or test, they should have the same features right? Why are they have to be different?
If the auxiliary data changes over time, I think you might want to fine-tune or re-train your model with the new features.

**Comment by Rico2000** [comment]
oke that is correct, of course. Sorry for my mistake.

**Comment by Rico2000** [comment]
Is there a possibility to include the auxiliary data with stratified split? In my case, the auxiliary data changes over time. So I want to use stratified split to train the model at a point in time with the respective auxiliary data to predict the future interactions? 
To do this, can I specify the auxiliary data at each point in time of the training or do they need to be constant over time. Thanks

**Comment by tqtg** [comment]
Sorry for not understanding your problem very well. Unfortunately, there is no functionality to support changing auxiliary data over time. You can try to create a new dataset whenever you want to change auxiliary data. Though I am not sure it would solve your problem the way you expect.
