### ISSUE TITLE
I would like to ask you the question about my use of cornac

### ISSUE THREAD

**Issue by newlinfeng-coder** [PreferredAI/cornac#425]
### Description

I would like to ask you the question about my use of cornac: when I downloaded the code to my local, I want to further expand this program. But the following error occurred during the test:

### In which platform does it happen?

windows 10

### How do we replicate the issue?

![image](https://user-images.githubusercontent.com/28260618/126928986-624befa6-7126-4c0e-990a-cbdead0dc3e7.png)

### Expected behavior (i.e. solution)

I am looking forward to your reply!

**Comment by tqtg** [comment]
Please build all Cython modules with the following command:
```bash
python setup.py build_ext --inplace
```
You also need to rerun the command everytime you change any Cython code for it to be effective.

**Comment by newlinfeng-coder** [comment]
> Please build all Cython modules with the following command:
> 
> ```shell
> python setup.py build_ext --inplace
> ```
> 
> You also need to rerun the command everytime you change any Cython code for it to be effective.

Thank you for your guidance. According to the above operations, setup.py has been run successfully. But i still have the following problems:
![image](https://user-images.githubusercontent.com/28260618/126951597-6bca9d50-db00-4dcb-b260-9e1154d6f146.png)

**Comment by tqtg** [comment]
The `.pyx` should be there if the Cython command finish successfully. Could you post the running log of the command?

**Comment by newlinfeng-coder** [comment]
yes，Specificially:
1.input      "python setup.py build_ext --inplace"
![image](https://user-images.githubusercontent.com/28260618/127085432-b03dd9db-b7ef-4fb8-8823-38409d362654.png)

2.cornac.models.comparer.recom_comparer_sub.pyx is as follows:
![image](https://user-images.githubusercontent.com/28260618/127085631-2bdbc0a2-85fe-449d-91aa-3d6c28e9e745.png)
It seems that there are many mistakes

Thank you again for your guidance. I am looking forward to your reply!

**Comment by newlinfeng-coder** [comment]
To supplement the previous question, the exception thrown by the program:
![image](https://user-images.githubusercontent.com/28260618/127085893-2557369f-b993-4f61-99a1-6305f722d3a3.png)

**Comment by tqtg** [comment]
I’m afraid this is due to PATH configuration in PyCharm. You need to set it properly for all the required modules to be imported.
One way to check if Cornac is built successfully is to run your code inside the root folder.

**Comment by newlinfeng-coder** [comment]
Maybe I did not express clearly, I am hoping to reuse the cornac's code, is directly downloaded from github, and then the underlying use of cornac to build, and did not use the form of pip to install.
![image](https://user-images.githubusercontent.com/28260618/127088704-bf120f75-4a7b-4e95-ad91-c6c6ce476038.png)
