### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by newlinfeng-coder** [PreferredAI/cornac#426]
### Description

I changed the office dataset to an amazon dataset in the c2pf example given by cornac, but found the following problem.

### In which platform does it happen?

linux ubuntu 14

### How do we replicate the issue?

![image](https://user-images.githubusercontent.com/28260618/127088198-0c03899c-ce16-4366-9eba-d972ab29b00f.png)

### Expected behavior (i.e. solution)

By checking online, it says that there is not enough memory to read the data at once. Do you have a good solution for the clothing dataset?

Thanks!

**Comment by newlinfeng-coder** [comment]
To add the previous question, my memory usage does not exceed:
![image](https://user-images.githubusercontent.com/28260618/127089293-c5e8a53e-a12e-4457-83d0-b0c8c8384f1c.png)

**Comment by tqtg** [comment]
@saghiles do you have any ideas on this issue?

**Comment by saghiles** [comment]
Hi, which dataset are trying to fit C2PF to, Clothing from Cornac?

**Comment by newlinfeng-coder** [comment]
> Hi, which dataset are trying to fit C2PF to, Clothing from Cornac?

yes, clothing from cornac

**Comment by saghiles** [comment]
Hi, the C2PF model requires the item graph (or item context in the paper) to be undirected (or with a symmetric adjacency matrix). The item graph in the clothing data is directed. The following code should fix the issue,

```ratings = amazon_clothing.load_feedback()
contexts = amazon_clothing.load_graph()
contexts = set(contexts)
contexts.update([(j, i, v) for (i, j, v) in contexts]) # making the adjacency matrix symmetric
contexts = list(contexts)
