### ISSUE TITLE
[ASK] BPR and VBPR

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [PreferredAI/cornac#430]
Hello

I am going through your VBPR tutorial https://github.com/PreferredAI/cornac/blob/master/tutorials/vbpr_text.ipynb. 
I previously used Microsoft recommender and they include BPR (modified from cornac) and in their tutorial https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/cornac_bpr_deep_dive.ipynb the precision@10 is 0.35 and recall@10 is 0.18

I modifed your tutorial with BPR model and use same hyperparameter with MS implementation ```dim=200, epochs=200, reg=1e-3, lr=0.01```, random split with test size 0.25. But I got very different result. Would you like to take a look and identify the source of the difference? My doubt would be it is due to the cornac.Experiment.

Thank you so much!

**Comment by Chen-Cai-OSU** [comment]
This is the modifed script based on your tutorial.

```
import cornac
from cornac.data import Reader
from cornac.datasets import movielens
from cornac.eval_methods import RatioSplit
from cornac.data import TextModality, ImageModality
from cornac.data.text import BaseTokenizer

print("Cornac version: {}".format(cornac.__version__))
plots, movie_ids = movielens.load_plot()

# movies without plots are filtered out by `cornac.data.Reader`
ml_100k = movielens.load_feedback(reader=Reader(item_set=movie_ids))

item_text_modality = TextModality(corpus=plots, ids=movie_ids,
                                  tokenizer=BaseTokenizer(sep='\t', stop_words='english'),
                                  max_vocab=5000, max_doc_freq=0.5).build()
features = item_text_modality.count_matrix.A
item_image_modality = ImageModality(features=features, ids=movie_ids)
ratio_split = RatioSplit(data=ml_100k, test_size=0.25, # change from 0.9 to 0.25 to make it the same as Microsoft recommender
                         item_image=item_image_modality,
                         exclude_unknowns=True,
                         verbose=True, seed=123,
                         rating_threshold=0, # what is the good value for this?
                         )
# vbpr = cornac.models.VBPR(k=10, k2=10, n_epochs=20, batch_size=10, learning_rate=0.001,
#                           lambda_w=1.0, lambda_b=0.0, lambda_e=100.0, use_gpu=True, seed=123)

# bpr = cornac.models.BPR(k=10, max_iter=100, learning_rate=0.001, lambda_reg=0.001, seed=123)
bpr = cornac.models.BPR(k=200, max_iter=200, learning_rate=0.01, lambda_reg=0.001, seed=123) # same parameters with Mircrosoft Recommender

pre = cornac.metrics.Precision(k=10)
rec = cornac.metrics.Recall(k=10)
cornac.Experiment(eval_method=ratio_split,
                  models=[bpr, ],
                  metrics=[pre, rec]).run()
```

The result I had is 
```
TEST:
...
    | Precision@10 | Recall@10 | Train (s) | Test (s)
--- + ------------ + --------- + --------- + --------
BPR |       0.1081 |    0.0979 |    6.9000 |   6.5462
```

which is much worse than the result from https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/cornac_bpr_deep_dive.ipynb

It would be super helpful if you can point out what causes such discrepancy.

**Comment by Chen-Cai-OSU** [comment]
I looked a bit deeper into the implementation and have the following questions
1) I saw there is no batch size arguments in  BPR model. Does it mean the model is optimized by full GD?
2) does it mean taking VBPR without item feature + set batch size = len(data), should gives us the essentially the same behavior of BPR? But it seems that VBPR is much slower than BPR implementation? Why?

Thank you!

**Comment by tqtg** [comment]
Quickly glance at your code, I could tell that you need to change two things:
1. Don't need to filter the items without movie plots. In fact, BPR doesn't use item text, and we don't filter such items in the example with Microsoft recommenders. Just simply do:
```python 
ml_100k = movielens.load_feedback()
```
2. Set `rating_threshold=1.0`, otherwise there is no notion of `positive feedback` and `negative feedback`, and all items are considered `positive` during evaluation.

Please take a look at this particular [example](https://github.com/PreferredAI/cornac/blob/master/examples/bpr_netflix.py) for BPR, and modify it accordingly with your dataset.
