### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by m93s** [PreferredAI/cornac#433]
### Description
For cornac models such as BPR, SVD, is there an option to fetch user/item latent vectors?
These are required for computing similar items and users.

### Other Comments
If the above feature is not present in the current API, is UserKNN and ItemKNN the recommended way to achieve this in the library?

**Comment by tqtg** [comment]
For BPR, you can take a look at #409. In general, you need to dive into the model implementation and obtain the user/item latent vectors accordingly.
