### ISSUE TITLE
[ASK] BiVAE with implicit data

### ISSUE THREAD

**Issue by LIMHARRY** [PreferredAI/cornac#434]
Hello

I'm Harry and I'm going through your BiVAE tutorial

https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/cornac_bivae_deep_dive.ipynb

And In this tutorial, the training data is Movielens 'userID', 'itemID', 'rating'.
But I want to use your algorithm with implicit (click, cart, order) data on e-commerce .
Do you have any advice to use your algorithm with implicit data?

Thank you

**Comment by tqtg** [comment]
It should be straightforward without much difference. If your data is binary, you can try `Bernoulli` likelihood which tends to converge faster and achieves good performance too.

**Comment by joc32** [comment]
Also try experimenting with different encoder structures and latent dimensions of the model.
