### ISSUE TITLE
[ASK] How can we load a new splited dataset?

### ISSUE THREAD

**Issue by rahmanidashti** [PreferredAI/cornac#439]
### Description
Hi. I am going to load a dataset that is splited into train, dev, and test dataset based on the timestamp (temporal split). How can we load such a dataset in the Cornac?

**Comment by tqtg** [comment]
If your dataset is already split into train, dev, and test, you can try to follow this [example](https://github.com/PreferredAI/cornac/blob/master/examples/given_data.py) with:
```python
BaseMethod.from_splits(..., fmt='UIRT')
```

Or if you want to split the data based on timestamp, you can use [StratifiedSplit](https://cornac.readthedocs.io/en/latest/eval_methods.html#cornac.eval_methods.stratified_split.StratifiedSplit) with:
```python
StratifiedSplit(..., fmt='UIRT', chrono=True)
```

**Comment by rahmanidashti** [comment]
Thank you. It is very helpful and solved my issues.
