### ISSUE TITLE
[BUG] Memory error on data/datasets.py 

### ISSUE THREAD

**Issue by ncsilvaa** [PreferredAI/cornac#440]
### Description

I am working with the Cornac library by using an external dataset (with around 70k users, 500k items, and 60k ratings),
and I've faced this error:

> MemoryError: Unable to allocate 214. GiB for an array with shape (64649, 445312) and data type float64

It happens in `data/dataset.py` when the code executes the build method.
In my opinion, it is happening because you are setting the r_values as `np.float` (line 366):

```
uir_tuple = (
            np.asarray(u_indices, dtype=np.int),
            np.asarray(i_indices, dtype=np.int),
            np.asarray(r_values, dtype=np.float),
        )
```

And, by default, NumPy will use float64 to represent the data.
It's not necessary to represent rating values. They are usually represented in small ranges.
Moreover, you can also analyse the highest value for u_indices and i_indices to make a downcast in the np.int as well. 

### In which platform does it happen?

I was using a DataBricks cluster with 10 workers of 56GB. 

### How do we replicate the issue?

I think you can replicate it by reading a huger dataset by these functions defined on datasets.py.
Based on what I saw in the code, I guess it does not happen when you the Netflix dataset (a huge one) 
because you use other functions where is not set these type transformations. 

### Expected behavior (i.e. solution)

I think the lib will be able to read larger external datasets after that.

### Other Comments

Anyway, the lib is really amazing! Congrats to all of you for this great job!

**Comment by tqtg** [comment]
It looks like you are trying to turn the rating matrix into a dense one. Could you show the code running your experiment?

**Comment by ncsilvaa** [comment]
Hey! I'm working with a pyspark dataframe.
So, I did:

```
dataset = cornac.data.Dataset.from_uirt(train_df.collect())
R = dataset.matrix.A
```

Should I read this data in another way?

**Comment by tqtg** [comment]
This `R = dataset.matrix.A` turns the rating matrix into a dense one, and I don't think you want to do that.

You can try to do this:
```python
train_data = train_df.collect()
test_data = test_df.collect()

eval_method = BaseMethod.from_splits(train_data=train_data, test_data=test_data)
```

Link to a full example: https://github.com/PreferredAI/cornac/blob/master/examples/given_data.py

**Comment by ncsilvaa** [comment]
Great! Thanks, @tqtg ! I think now is running. 
Do you know how can I get the predictions as well? 

Moreover, can I close this issue or would you like to use it to improve the dense representation?

**Comment by tqtg** [comment]
If you mean predictions of the model, you can call `model.rate()` or `model.rank()` functions. Please refer to the [documentation](https://cornac.readthedocs.io/en/latest/models.html) for more details.

And yes, feel free to close this issue.

**Comment by ncsilvaa** [comment]
Thanks for all!
