### ISSUE TITLE
Implementation of APR and AMR

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#445]
### Description
Hello, thanks for implementing AMR within Cornac. AMR is an extension of APR (Adversarial Bayesian Personalized Ranking), and to have a complete evaluation system, I was wondering if it would be possible to use APR within cornac. In particular, (i) if existing AMR implemented could be switched down to APR e.g., by setting the features/params to zero, (ii) if you could consider implementing APR directly. Thank you for the feedbacks!

**Comment by tqtg** [comment]
Currently, APR is not available in Cornac. Based on my understanding, it should be straightforward to modify the current implementation of AMR to APR. Feel free to [contribute the model](https://github.com/PreferredAI/cornac/blob/master/tutorials/add_model.md) to Cornac if you plan to do so.
