### ISSUE TITLE
[ASK] How can evaluate on leave-one-out test set?

### ISSUE THREAD

**Issue by rahmanidashti** [PreferredAI/cornac#447]
Hi, does Cornac support leave-one-out test data for evaluation? Suppose our train file is in UIR format but our test set is as follows:

UserID \t Item1, Item2, Item3, ...., Item100

in which only one item out of these 100 items are positive instance.

**Comment by tqtg** [comment]
You can try [StratifiedSplit](https://cornac.readthedocs.io/en/latest/eval_methods.html#module-cornac.eval_methods.stratified_split) with `test_size=1`. You might need to change the format of your data cause it's not UIR.
