### ISSUE TITLE
[ASK] Proper feeding of methods

### ISSUE THREAD

**Issue by alitourani** [PreferredAI/cornac#448]
Hello,

The item-KNN method in Cornac uses, by default, ratings (interaction) to compute Item-Item similarities. Is it possible to use the same method but feed it with pre-computed similarities (e.g., the similarity among visual features) using content data and/or combined with rating to build a hybrid model?

Another similar question is about the FM method. Is it possible to feed feature vectors of item content (e.g., visual features) and use FM? It seems no example is provided.

**Comment by tqtg** [comment]
1. You might want to change the way [similarity matrix](https://github.com/PreferredAI/cornac/blob/2de81e17b83794a3e7cbc4f47d6bd9061694b5d1/cornac/models/knn/recom_knn.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L382) is computed, either by reassigning the values or modifying the code a bit.
2. Current implementation of `FM` doesn't support additional features, only user-item interactions are considered.

**Comment by alitourani** [comment]
Thank you for the feedback.

Good to know about FM!
Regarding the second remark, I am still not sure how I can the method you suggested (sorry maybe due to my misunderstanding). What I basically want is to feed the system with (i) pre-computed features, or (ii) item-content feature vectors to one of the Cornac models.

With VBPR it seems we have performance issues and not being able to build a visual recommender system.

**Comment by tqtg** [comment]
It depends on what model you want to use, and what kind of features/modalities the model can take in as input. We have tried to organize the [examples](https://github.com/PreferredAI/cornac/tree/master/examples) into categories.

If you implement your own model, you can feed the features into [FeatureModality](https://cornac.readthedocs.io/en/latest/data.html#cornac.data.modality.FeatureModality) either on the user or item side.

**Comment by alitourani** [comment]
Thanks a lot.
