### ISSUE TITLE
[BUG] AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by giuliodavide** [PreferredAI/cornac#449]
### Description
I tried to run the example conv_mf_example.py but it returns me this error.

### In which platform does it happen?
I tried it in Windows and in Google Colab.

### How do we replicate the issue?
Just run `conv_mf_example.py` with `python3 conv_mf_example.py`

### Expected behavior (i.e. solution)
The experiment should run successfully and output the results.

### Other Comments
Here it is the traceback of the error in Colab.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-03286c994a5b> in <module>()
     40 # Put everything together into an experiment and run it
     41 cornac.Experiment(
---> 42     eval_method=ratio_split, models=[convmf], metrics=[rmse], user_based=True
     43 ).run()

/usr/local/lib/python3.7/dist-packages/cornac/experiment/experiment.py in run(self)
    133                 metrics=self.metrics,
    134                 user_based=self.user_based,
--> 135                 show_validation=self.show_validation,
    136             )
    137 

/usr/local/lib/python3.7/dist-packages/cornac/eval_methods/base_method.py in evaluate(self, model, metrics, user_based, show_validation)
    698 
    699         start = time.time()
--> 700         model.fit(self.train_set, self.val_set)
    701         train_time = time.time() - start
    702 

/usr/local/lib/python3.7/dist-packages/cornac/models/conv_mf/recom_convmf.py in fit(self, train_set, val_set)
    165 
    166         if self.trainable:
--> 167             self._fit_convmf()
    168 
    169         return self

/usr/local/lib/python3.7/dist-packages/cornac/models/conv_mf/recom_convmf.py in _fit_convmf(self)
    218             seed=self.seed,
    219             init_W=self.W,
--> 220             learning_rate=self.cnn_lr,
    221         )
    222 

/usr/local/lib/python3.7/dist-packages/cornac/models/conv_mf/convmf.py in __init__(self, output_dimension, dropout_rate, emb_dim, max_len, filter_sizes, num_filters, hidden_dim, seed, init_W, learning_rate)
     86         self.vanila_dimension = hidden_dim
     87 
---> 88         self._build_graph()
     89 
     90     def _build_graph(self):

/usr/local/lib/python3.7/dist-packages/cornac/models/conv_mf/convmf.py in _build_graph(self)
     90     def _build_graph(self):
     91         # create Graph
---> 92         self.model_input = tf.placeholder(dtype=tf.int32, shape=(None, self.max_len))
     93         self.v = tf.placeholder(dtype=tf.float32, shape=(None, self.output_dimension))
     94         self.sample_weight = tf.placeholder(dtype=tf.float32, shape=(None,))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by tqtg** [comment]
ConvMF uses TensorFlow version 1, you might be using version 2 instead. If you're using GG Colab, you can try [this](https://colab.research.google.com/notebooks/tensorflow_version.ipynb).

**Comment by giuliodavide** [comment]
@tqtg it worked, thanks a lot.
