### ISSUE TITLE
[ASK] How we can avoid removing the duplicate observations in build dataset?

### ISSUE THREAD

**Issue by rahmanidashti** [PreferredAI/cornac#453]
### Description

Hi guys, when we load datasets using Cornac built-in functions, in `build` function you remove and avoid duplicated interactions (uid, iid), however, in some cases, like check-in datasets this always happens. So, is there a way to avoid removing duplicated interactions? Or I think you should this feature into the dataset class.

**Comment by tqtg** [comment]
Yes, that's the default behavior at the moment, otherwise, the input data should be pre-processed (e.g., sum up the interactions).  We will look into the possibility of allowing users to define a lambda aggregator function.

**Comment by rahmanidashti** [comment]
Thanks for your response.
