### ISSUE TITLE
[ASK]Adding different types of information to matrix

### ISSUE THREAD

**Issue by amil-khare** [PreferredAI/cornac#454]
### Description
 
Hello, 
I had a question regarding extra metadata that can be added to models in 2 different scenarios:

- Scenario 1
  -  Adding Implicit rating(clicks) and explicit rating(1-5) to matrices. Should I figure out the scoring function myself or is there some way to handle such cases
- Scenario 2
  -  Adding User & Item meta data along side implicit ratings. These metadata can be categorical, text and continuous valued set of features. Which models have the support for such use cases?

### Other Comments
- Also one more question I had was around best way to go about training for large datasets? Create multiple Training & Validation CSV files?

**Comment by tqtg** [comment]
- Scenario 1: not quite understand your situation. If you have both implicit and explicit matrices, then you might want to use either one of them. Alternatively, you can try to combine them into one unified user-item interaction matrix.
- Scenario 2: these forms of metadata/auxiliary data we call modalities in Cornac. You can take a look at [list of examples](https://github.com/PreferredAI/cornac/tree/master/examples) to see which model fits your need depending on the type of modality as well as which side (user/item) the modality is available.

**Comment by amil-khare** [comment]
@tqtg Thanks for the response!

- Scenario 2: I have categorical data like - Genre of Movies, User Age bracket. What type of modality would they be coming in?

- Scenario 3: I also wanted to know how can I run cornac on really huge data. I am using Pyspark for processing data and have about 10 million records. Should I break down the data into multiple csv files and if so is there a tutorial how to pass multiple files to train a model?

**Comment by tqtg** [comment]
- Scenario 2: those data can be turned into feature vectors using some form of encoding (e.g., one-hot, multi-hot), then fed into [FeatureModality](https://cornac.readthedocs.io/en/latest/data.html#cornac.data.FeatureModality). [This](https://github.com/PreferredAI/bi-vae/blob/main/bivae_cap.py) could be a good example for working with FeatureModality.
- Scenario 3: you might want to work with a small subset of your data and figure out a good model candidate first, before going to scale up to the whole dataset. A large dataset could be a problem with neural network-based models, though some of them work well with bigger datasets than yours (e.g., Netflix, MovieLens 20M).

Anyway, this is going off the topic of your initial question. Please consider closing this issue and open new ones if you face technical problems.
