### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by deychak** [PreferredAI/cornac#455]
### Description

Great library! Is there a mechanism to remove already seen/liked/interacted-with items upon prediction for some model? MS Recommenders uses [this](https://github.com/microsoft/recommenders/blob/main/recommenders/models/cornac/cornac_utils.py#L56).

**Comment by tqtg** [comment]
Hi, it depends on your use case. For the pipeline within Cornac, [the already seen interactions during training will be removed during evaluation](https://github.com/PreferredAI/cornac/blob/2de81e17b83794a3e7cbc4f47d6bd9061694b5d1/cornac/eval_methods/base_method.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L184). 

If you want to predict the whole matrix as similar to MS Recommenders, you can make use of that utility function which is also developed by our team for compatibility with the MS Recommenders' evaluation pipeline.

**Comment by deychak** [comment]
@tqtg it seems the utility function in MS Recommenders [only considers users in the train set](https://github.com/microsoft/recommenders/blob/main/recommenders/models/cornac/cornac_utils.py#L73). If a Cornac model supports cold users, it wouldn't consider them here. Is that correct? Cornac, though, offers a flag during within evaluation to exclude or include unknown users/items.

**Comment by deychak** [comment]
Apologies for opening and reopening 🤦 .

Could you please point out how your linked line of code is used by the Recall@K metric in Cornac, specifically for filtering out already seen interactions? You've linked `train_pos_items` which is used by `u_gt_neg`. Although that is passed to `mt.compute`, I don't see how that is used by the `class Recall(MeasureAtK)` metric. 

<img width="1786" alt="Screen Shot 2021-12-21 at 11 03 47 PM" src="https://user-images.githubusercontent.com/6568233/147034040-58e7e8e3-fa66-497d-bbe5-a1c23a3c57e9.png">

The reason why I ask is I've been experimenting with MS Recommenders evaluation and comparing Cornac evaluation. I'm using the same train and test data across both and computing recall@k for both. I seem to be getting the same numbers when in MS Recommenders I set `remove_seen=False` and in Cornac I just keep `exclude_unknowns=True` as MS Recommenders (cornac_utils) only look at users in the train set anyway. This makes me think that Cornac isn't automatically removing already interacted with items upon recommendation. Any thoughts on this?

**Comment by tqtg** [comment]
Removing seen items is done in a centralized way and used for all metrics during evaluation. When inputting to `compute()` function of any metric, all seen items during training are flagged and not considered. 

MS Recommenders assumes all users and items are known during evaluation, which is equivalent to setting `exclude_unknowns=True` in Cornac. They don't deal with unknown users/items at all.

**Comment by deychak** [comment]
>MS Recommenders assumes all users and items are known during evaluation, which is equivalent to setting exclude_unknowns=True in Cornac. They don't deal with unknown users/items at all.

Thanks for confirming that.

>Removing seen items is done in a centralized way and used for all metrics during evaluation. When inputting to compute() function of any metric, all seen items during training are flagged and not considered.

Do you mind linking me how this happens specifically for recall@k?

**Comment by tqtg** [comment]
For Recall@K, we only need to consider the hold-out positive items in the test set, and those items are indicated in the`u_gt_pos` array.

**Comment by deychak** [comment]
>For Recall@K, we only need to consider the hold-out positive items in the test set, and those items are indicated in the u_gt_pos array.

Right and that I can trace that in the code but what happens if one of those items indicated in the test set (for some user) also exist in the train set (for the same user) meaning it is an "already seen" interaction. I can't seem to find the code that would handle the "removal" in evaluation per your guidance from:

> Hi, it depends on your use case. For the pipeline within Cornac, the already seen interactions during training will be removed during evaluation.

**Comment by tqtg** [comment]
The assumption is that each user-item interaction is unique, meaning it either appears in train or test. The duplicates are removed during data loading [here](https://github.com/PreferredAI/cornac/blob/2de81e17b83794a3e7cbc4f47d6bd9061694b5d1/cornac/data/dataset.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L347).

**Comment by deychak** [comment]
>The duplicates are removed during data loading here.

Yes. This is my understanding as well. Thanks.

Imagine a disjoint dataset scenario where interaction data is pulled for one month (train) and loaded as a Cornac dataset then data is pulled for the following month (test) and loaded into a test Cornac dataset similar to what we see in this Cornac [example](https://github.com/PreferredAI/cornac/blob/1e5c9794ee04567597c966f241af7f82113702bb/examples/given_data.py#L34).  This means users and items can exists in both train and test.

I do not see any code in the recall@k ranking metric that would indicate that already interacted with items in train are filtered out of the model's predictions within the evaluation routine. It is my understanding that already interacted with items are actually not filtered out in this case.

**Comment by tqtg** [comment]
OK. Actually, the logic is that we remove duplicates within train/test dataset but not across datasets. The reason is that multiple interactions between the same pair of user-item could be incurred with different timestamps. This is to cater to the sequential recommendation problem in which the same user-item interactions in the future (in the test set with different timestamps) could as well be positive labels as unseen interactions. I guess this is exactly the scenario that you described.

Sorry that I'm not quite clear about your motivation. If you want to completely remove already seen interactions in training, then a simple approach is to filter such interactions in the test data before building the test set. I don't think modifying recall@k or any other metrics is a scalable way to go.

**Comment by deychak** [comment]
> I don't think modifying recall@k or any other metrics is a scalable way to go.

Agreed - this should not be modified. 

Just to be clear, my original ask was to dig into how Cornac handles already seen interactions. From our conversation thus far, they are not explicitly removed in any of the metric(s) or evaluation(s) code but are filtered out as dupes if they exist within the same Cornac dataset.

Tangentially, I'm not sure if this filtration of duplicates per dataset is the best strategy because repeat interactions can occur across many domains, e.g., e-commerce. I'd imagine a possibility that some sequential model may train on UIRT (time sorted) interaction data where repeat interactions are not only permitted but anticipated within the train set. One way to offer a bit more flexibility is to allow repeat interactions when building the Cornac dataset given some flag but then offer a parameter for a lambda aggregation of them if need be.

**Comment by tqtg** [comment]
> One way to offer a bit more flexibility is to allow repeat interactions when building the Cornac dataset given some flag but then offer a parameter for a lambda aggregation of them if need be.

Thanks for the suggestion. That's exactly what we're planning to do, offering lambda aggregation for dealing with duplicate interactions. Happy to discuss more on that.

**Comment by deychak** [comment]
Awesome. Thanks again for your support on this ASK.
