### ISSUE TITLE
[ASK] Hybrid model using audio features

### ISSUE THREAD

**Issue by giuliodavide** [PreferredAI/cornac#456]
### Description
Hi guys,
thank you in advance for your availability.
I wanted to ask you if there's a possibility to use an hybrid model in Cornac which also uses audio features, thus building a hybrid collaborative + content-based model. I have two possibilities: compute similarities among audio features of different items or feed the model with vector features.
In Cornac we already have very good text-based, image-based and graph-based models, but unfortunately they don't allow us to use audio features. They come with audio processing and text processing steps that does not allow us to feed audio features at least in a straightforward manner. The features we have extracted come from a newly relesed dataset and are continues feature vector. We would like to use cornac for this, Is there a way to use them in your system? Many thanks.

**Comment by saghiles** [comment]
Hi, audio specific processing have to be curried outside of Cornac, you can then use the framework to integrate audio extracted information to some recommender models. 
* For the first use case, it seems you are interested in building a graph of items based on audio similarities. The following [tutorial](https://github.com/PreferredAI/cornac/blob/master/tutorials/text_to_graph.ipynb) should help. 
* If instead you work with vector features, then you may rely on the ``FeatureModality`` class and instantiate it with your audio features.
This [series](https://github.com/PreferredAI/cornac/tree/master/tutorials#multimodality) of tutorials on Multimodality may be useful. If you are interested in having the audio preprocessing steps in Cornac, you may consider adding an ``AudioModality`` class, which would be a great contribution to the framework :).  

Thank you.

**Comment by tqtg** [comment]
In order to use item's `FeatureModality` with BiVAECF, you need to set:
```python 
cap_priors={'user': False, 'item': True}
```

**Comment by giuliodavide** [comment]
Thank you, it worked.
For my work of thesis I would like also to use other models compatible with `FeatureModality` object, are there any other? From your examples I only found this one.
Thank you again and sorry to bother you.

**Comment by saghiles** [comment]
Great that it worked. If you are interested in using the MCF model (which works with graph of items) you'll need to build an item graph from the audio features. This [tutorial](https://github.com/PreferredAI/cornac/blob/master/tutorials/text_to_graph.ipynb) should help. Examples of other models you can consider are  VBPR, CDL, CVAE. The latter work with image/text features, and maybe you can pass the audio features as if they were image/text features.
