### ISSUE TITLE
Item-to-Item and User-to-User Receommendation

### ISSUE THREAD

**Issue by srijiths** [PreferredAI/cornac#457]
### Description

Using BiVAE and BiVAE_CAP algorithms

Using the model.rank() method, i was able to get the top 'K' items recommendation for a given user.  

I like to get the top 'K' item recommendations for a given item.
I like to get the top 'K' user recommendations for a given user.

I assume that , currenly model.rank() is only for user to item prediction. It would be a great help if you can point which direction i should go to tackle above requirement. 

### Expected behavior (i.e. solution)

For a given item , recommend top 'K' similar items
For a given user , recommend top 'K' similar users
### Other Comments

**Comment by srijiths** [comment]
It would be a great help, if anybody can give me some pointers on this. 

Thank You

**Comment by tqtg** [comment]
It seems that you're tackling a similarity learning problem rather than personalized recommendation. Cornac APIs are mainly designed to facilitate the latter. Anw, if you find some models in Cornac useful for your problem, you can customize the `rank()` function to fit the needs.

**Comment by srijiths** [comment]
@tqtg Thank you for the reply. I understand your point.

**Comment by saghiles** [comment]
Hi, if you are interested in getting to the top k users for a given item, you may consider flipping the user and item sets in your dataset.

**Comment by srijiths** [comment]
@saghiles thank you. I will try and update.
