### ISSUE TITLE
[FEATURE] Time-wise wrapper for all models

### ISSUE THREAD

**Issue by vlainic** [PreferredAI/cornac#458]
### Description

I have used your UIRT data format, but this did not help for my case at all even though I would expect it does. But I have found an interesting framework/wrapper approach that could be implemented with any model. So it might sound interesting for you guys.

### Expected behavior with the suggested feature

The idea is very simple - using [SLRC paper](http://www.thuir.cn/group/~YQLiu/publications/WWW2019Wang.pdf) and it's [github implementation](https://github.com/THUwangcy/SLRC) to make time-wrapper for better leveraging of time information.

### Other Comments

If you want, I could help coding part too :)

**Comment by tqtg** [comment]
Thanks for pointing out the interesting resources. We will try to take a look, and of course we welcome your contributions.

**Comment by saghiles** [comment]
Hi, thanks for this suggestion. 
- Could you please clarify what is the connection between the UIRT format and the SLRC method? 
- How does SLRC work, and how does it affect existing recommender models? For instance, given a recommender model (e.g., BPR) do we need to change its objective functions?
Thank you.

**Comment by vlainic** [comment]
> Hi, thanks for this suggestion.
> 
> * Could you please clarify what is the connection between the UIRT format and the SLRC method?
> * How does SLRC work, and how does it affect existing recommender models? For instance, given a recommender model (e.g., BPR) do we need to change its objective functions?
>   Meanwhile we are taking a look at the paper.
>   Thank you.

Hello,

In my understanding (that might be wrong) of your UIRT is that adds the time dimension to the training, **OR** is it just a time-wise dataset sorting/split? In the latter case, there is no connection :)

For `cornac` the key sentence from the SLRC paper would be the one from the conclusion "Generally, our model is able to be leveraged as a framework that utilizes repeat consumption information to enhance existing recommender systems based on collaborative filtering...". Henceforth it can be seen as **the time-wise wrapper** for any recommender and I don't think that any objective functions should be changed, i.e. model is flexible around that. The "only" relevant thing (IMO) is that there might be some careful implementation of the SLRC as the wrapper to make it compatible with all the tools in `cornac`.

Thank you for the replies and consideration.
