### ISSUE TITLE
[BUG] Error on import cornac library

### ISSUE THREAD

**Issue by muhammad49** [PreferredAI/cornac#459]
### Description
I simply installed "cornac" through pip on azure cluster and tried to import it like this in notebook same import is working for me on my local but throwing error on azure.
"import cornac"
which throws the following error
"
ImportError                               Traceback (most recent call last)
<command-1454593970550517> in <module>
----> 1 import cornac

/databricks/python/lib/python3.7/site-packages/cornac/__init__.py in <module>
     14 # ============================================================================
     15 
---> 16 from . import data
     17 from . import datasets
     18 from . import eval_methods

/databricks/python/lib/python3.7/site-packages/cornac/data/__init__.py in <module>
     16 from .modality import Modality
     17 from .modality import FeatureModality
---> 18 from .text import TextModality, ReviewModality
     19 from .image import ImageModality
     20 from .graph import GraphModality

/databricks/python/lib/python3.7/site-packages/cornac/data/text.py in <module>
     25 from . import FeatureModality
     26 from .modality import fallback_feature
---> 27 from ..utils import normalize
     28 
     29 __all__ = ['Tokenizer',

/databricks/python/lib/python3.7/site-packages/cornac/utils/__init__.py in <module>
     14 # ============================================================================
     15 
---> 16 from .common import validate_format
     17 from .common import estimate_batches
     18 from .common import get_rng

/databricks/python/lib/python3.7/site-packages/cornac/utils/common.py in <module>
     19 import scipy.sparse as sp
     20 
---> 21 from .fast_sparse_funcs import (
     22     inplace_csr_row_normalize_l1,
     23     inplace_csr_row_normalize_l2

ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
"

### In which platform does it happen?
Azure Databricks Cluster Version 6.4 ML (includes Apache Spark 2.4.5, Scala 2.11)
python 3.7

**Comment by muhammad49** [comment]
Yes by setting libpython that error is fixed but throwing another error which is 

`
ImportError                               Traceback (most recent call last)
<command-1454593970550517> in <module>
----> 1 import cornac

/databricks/python/lib/python3.7/site-packages/cornac/__init__.py in <module>
     16 from . import data
     17 from . import datasets
---> 18 from . import eval_methods
     19 from . import models
     20 from . import metrics

/databricks/python/lib/python3.7/site-packages/cornac/eval_methods/__init__.py in <module>
     14 # ============================================================================
     15 
---> 16 from .base_method import rating_eval
     17 from .base_method import ranking_eval
     18 

/databricks/python/lib/python3.7/site-packages/cornac/eval_methods/base_method.py in <module>
     29 from ..metrics import RatingMetric
     30 from ..metrics import RankingMetric
---> 31 from ..experiment.result import Result
     32 from ..utils import get_rng
     33 

/databricks/python/lib/python3.7/site-packages/cornac/experiment/__init__.py in <module>
     14 # ============================================================================
     15 
---> 16 from .experiment import Experiment
     17 from .result import Result
     18 from .result import ExperimentResult

/databricks/python/lib/python3.7/site-packages/cornac/experiment/experiment.py in <module>
     21 from ..metrics.rating import RatingMetric
     22 from ..metrics.ranking import RankingMetric
---> 23 from ..models.recommender import Recommender
     24 
     25 

/databricks/python/lib/python3.7/site-packages/cornac/models/__init__.py in <module>
     26 from .cdr import CDR
     27 from .coe import COE
---> 28 from .comparer import ComparERObj
     29 from .comparer import ComparERSub
     30 from .conv_mf import ConvMF

/databricks/python/lib/python3.7/site-packages/cornac/models/comparer/__init__.py in <module>
     15 
     16 from .recom_comparer_sub import ComparERSub
---> 17 from .recom_comparer_obj import ComparERObj

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /databricks/python/lib/python3.7/site-packages/cornac/models/comparer/recom_comparer_obj.cpython-37m-x86_64-linux-gnu.so)
`

**Comment by muhammad49** [comment]
Is there any guidelines or step tutorials on how can I install and setup cornac on azure cluster?

**Comment by tqtg** [comment]
#462
