### ISSUE TITLE
[ASK] Creating batches that allow for training of models on large data

### ISSUE THREAD

**Issue by amil-khare** [PreferredAI/cornac#461]
### Description

Hello @tqtg 
I want to train the models on large data like Netflix Prize and others and hence would like to understand how would I train models like BPR  using batches. Currently i have multiple CSV files on my S3 bucket each having about 10K user item interactions. I cannot read the whole dataset into my memory, hence would like to read batches of CSV files from s3 and perform training. 
Can anyone help me with the relevant piece of code?

### Other Comments
Unfortunately I cannot get higher memory. As for training with smaller data I have observed very poor performance.

**Comment by tqtg** [comment]
If those multiple CSV files share the same set of users and items, then a simple approach is to write a loop to read those files sequentially. Inside the loop, you read a CSV file and build a [Dataset](https://cornac.readthedocs.io/en/latest/data.html#cornac.data.dataset.Dataset) based on the file, then fit the BPR model on such dataset. BPR is trained using stochastic gradient descent so this approach should be equivalent to training on the big dataset if you have enough memory to load the whole thing at once. One suggestion is to set `max_iter=1` for the BPR and control how long you want to train the model using the outer loop. 

[This tutorial](https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/cornac_bpr_deep_dive.ipynb) has some useful pieces of code to build a dataset and fit the BPR model. Hope this helps!
