### ISSUE TITLE
[BUG] Import Error on Azure notebook

### ISSUE THREAD

**Issue by muhammad49** [PreferredAI/cornac#462]
### Description
After installing cornac and required dependencies on azure cluster also setting up libpython in environment variables I am facing this error

`
ImportError Traceback (most recent call last)
in
----> 1 import cornac

/databricks/python/lib/python3.7/site-packages/cornac/init.py in
16 from . import data
17 from . import datasets
---> 18 from . import eval_methods
19 from . import models
20 from . import metrics

/databricks/python/lib/python3.7/site-packages/cornac/eval_methods/init.py in
14 # ============================================================================
15
---> 16 from .base_method import rating_eval
17 from .base_method import ranking_eval
18

/databricks/python/lib/python3.7/site-packages/cornac/eval_methods/base_method.py in
29 from ..metrics import RatingMetric
30 from ..metrics import RankingMetric
---> 31 from ..experiment.result import Result
32 from ..utils import get_rng
33

/databricks/python/lib/python3.7/site-packages/cornac/experiment/init.py in
14 # ============================================================================
15
---> 16 from .experiment import Experiment
17 from .result import Result
18 from .result import ExperimentResult

/databricks/python/lib/python3.7/site-packages/cornac/experiment/experiment.py in
21 from ..metrics.rating import RatingMetric
22 from ..metrics.ranking import RankingMetric
---> 23 from ..models.recommender import Recommender
24
25

/databricks/python/lib/python3.7/site-packages/cornac/models/init.py in
26 from .cdr import CDR
27 from .coe import COE
---> 28 from .comparer import ComparERObj
29 from .comparer import ComparERSub
30 from .conv_mf import ConvMF

/databricks/python/lib/python3.7/site-packages/cornac/models/comparer/init.py in
15
16 from .recom_comparer_sub import ComparERSub
---> 17 from .recom_comparer_obj import ComparERObj

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.27' not found (required by /databricks/python/lib/python3.7/site-packages/cornac/models/comparer/recom_comparer_obj.cpython-37m-x86_64-linux-gnu.so)
`

### In which platform does it happen?
Azure Databricks Cluster Version 6.4 ML (includes Apache Spark 2.4.5, Scala 2.11)
python 3.7

**Comment by tqtg** [comment]
These are dependency issues. Please follow the error traces and fix them according to your OS and environment. If Ubuntu, updating the packages might help:
```bash
$ apt-get update
$ apt-get install build-essential -y
```

**Comment by tqtg** [comment]
Some particular versions of python might cause this issue as well. You might want to change the version of python in the Azure environment. Maybe try to use 3.8 instead?

**Comment by gsy44355** [comment]
> These are dependency issues. Please follow the error traces and fix them according to your OS and environment. If Ubuntu, updating the packages might help:
> 
> ```shell
> $ apt-get update
> $ apt-get install build-essential -y
> ```

I have try ```yum groupinstall "Development Tools"``` command   on my centos7 linux machine. I still have *version `GLIBC_2.27' not found* error when I import cornac
