### ISSUE TITLE
[FEATURE] cv metrics output averages to dict

### ISSUE THREAD

**Issue by deychak** [PreferredAI/cornac#464]
### Description

Is there an easy way to get the metric average's from the `CVResult` when running an `Experiment` for cross validation? Is it possible to return a dictionary that has the actual averages as shown in the output print and file?

https://github.com/PreferredAI/cornac/blob/2de81e17b83794a3e7cbc4f47d6bd9061694b5d1/cornac/experiment/result.py#L76

**Comment by tqtg** [comment]
`mean` and `std` of CV are computed on the fly and we don't store them. You can obtain a `CVResult` object from an [`Experiment`](https://github.com/PreferredAI/cornac/blob/2de81e17b83794a3e7cbc4f47d6bd9061694b5d1/cornac/experiment/experiment.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L82) for the purpose of recomputing the average if needed.

**Comment by deychak** [comment]
That is what I am doing now. Is it possible to add this as a feature, i.e., return the mean and std per metric as part of the CVResult?

**Comment by tqtg** [comment]
That seems reasonable, we can store `mean` and `std` as attributes of `CVResult` using dictionary with metrics as keys.

**Comment by deychak** [comment]
Awesome - can we track the progress for that here?

**Comment by tqtg** [comment]
#467
Added in the code, should be available in the next release

**Comment by deychak** [comment]
Thanks! This is great!
