### ISSUE TITLE
Extract item embeddings - VAECF model

### ISSUE THREAD

**Issue by PaulCristina** [PreferredAI/cornac#468]
### Description
Hi , could you please tell me how to extract the trained item embeddings for the VAECF model?

**Comment by tqtg** [comment]
I don't think VAECF contains item embeddings unless you're referring to a set of model parameters. If you could elaborate more on the purpose of extracting item embeddings, we might have a better idea to help.

**Comment by tqtg** [comment]
BPR is an MF-based model thus there are user and item factors. VAECF is a different type of model with auto-encoder architecture so there are only user embeddings. If you want the best of both worlds, you can take a look at the BiVAECF model.

**Comment by PaulCristina** [comment]
And for BIVAECF there is a way to extract the latent factors for the items?

**Comment by tqtg** [comment]
Yes. For BiVAECF, you can extract user and item embeddings with `model.mu_theta` and `model.mu_beta`, respectively.

**Comment by PaulCristina** [comment]
Thank you
