### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by deychak** [PreferredAI/cornac#470]
### Description

Is it possible to use the hyperparameter tuning mechanism in this library with this libraries cross validation evaluation method? I tried it but once it is complete, I am unable to retrieve `best_params`. However, if I switch over to `RatioSplit` as the eval method instead of the cross validation eval method, I am able to access `best_params`. Is this a bug?

```
hpt_model = {{some model}}
hpt_metric = {{some metric}}
hpt_space = [
  cr_hpt.Discrete("some_param", [32, 64, 128, 256, 512]),
  cr_hpt.Discrete("some_param", [150, 250, 350]),
  cr_hpt.Discrete("some_param", [0.001, 0.01, 0.1, 1.0]),
  cr_hpt.Discrete("some_param", [0.001, 0.01, 0.1, 1.0]),
]
# hpt_eval = cr.eval_methods.RatioSplit(
#     data=data, 
#     test_size=0.1, 
#     val_size=0.1,
#     seed=SEED,
#     rating_threshold=1.0,
#     exclude_unknowns=True,
#     verbose=True,
# )
hpt_eval=cr.eval_methods.CrossValidation(
    data=data,
    n_folds=5,
    rating_threshold=1.0,
    partition=None,
    seed=SEED,
    exclude_unknowns=True,
    verbose=True,
)
gs_model = cr_hpt.GridSearch(
    model=hpt_model,
    space=hpt_space,
    metric=hpt_metric,
    eval_method=hpt_eval,
)
hpt_experiment = cr.Experiment(
    eval_method=hpt_eval,
    models=[gs_model],
    metrics=[hpt_metric],
    user_based=True,
    verbose=True,
)
hpt_experiment.run()
# doesn't work w/ cross val
print(gs_model.best_params) 
```

**Comment by tqtg** [comment]
The current `hyperopt` is not designed for CV. If it's being used with CV, the best params are searched for each fold independently, not the best average of all folds. That's not the way it should be.

**Comment by deychak** [comment]
I see. I was thinking something similar to sklearn's hyperparameter search with cross validation as shown in the [user guide](https://scikit-learn.org/stable/modules/grid_search.html). Sounds like this is not supported. Thanks!
