### ISSUE TITLE
[ASK] issue with Amazon Digital Music?

### ISSUE THREAD

**Issue by Sergiostef25** [PreferredAI/cornac#471]
### Description

I would like to use the "Amazon Digital Music" dataset, which is present in the built-in dataset table of cornac, but when i load it, i receive the error message:
`module 'cornac.datasets' has no attribute 'amazon_music'`

Is this dataset no longer supported?

**Comment by tqtg** [comment]
@lthoang could you help check with this issue?

**Comment by lthoang** [comment]
@tqtg, the connection to host static.preferred.ai is currently down. I will inform you ASAP when it is available.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/2834268/162581669-564389b8-a609-4a79-a3c0-206d47a390c0.png">

**Comment by lthoang** [comment]
Hi @Sergiostef25,

You can now use the dataset as follows:

```
from cornac.datasets import amazon_digital_music


ratings = amazon_digital_music.load_feedback()
reviews = amazon_digital_music.load_review()
```

**Comment by Sergiostef25** [comment]
@lthoang it works, thank you!
