### ISSUE TITLE
[BUG] Can't run propensity_stratified_evaluation_example.py

### ISSUE THREAD

**Issue by WideSu** [PreferredAI/cornac#474]
### Description

Good afternoon!
I tried to run the example for [propensity stratified evaluation](https://github.com/PreferredAI/cornac/blob/master/examples/propensity_stratified_evaluation_example.py) but can't import **PropensityStratifiedEvaluation**. Maybe someone deleted it by accident.
![image](https://user-images.githubusercontent.com/44923423/168463396-d1b8a102-faaa-4827-b0e2-79b83726609c.png)

### Other Comments
Thanks for your hard work, cool repository and thanks for the lessons!

**Comment by saghiles** [comment]
Hi, on my side it works fine. Please make sure you install the latest  version of Cornac it should fix the issue. 

I am closing this issue. If the error persists after installing the latest version of Cornac, please do not hesitate to reopen this issue.
