### ISSUE TITLE
[ASK] How to test all available models on an e-commerce site?

### ISSUE THREAD

**Issue by almirb** [PreferredAI/cornac#475]
### Description
Hello!
We have some e-commerce websites (majority on fashion and decoration) and we're planning what's the best way to provide recommendations for users (when viewing a product or on basket phase).

The current features to work on are user x item interactions, item titles/descriptions and product images. 
Would It be possible to use Cornac (with all included models) to help us to decide on what kind of recommender system would perform better?

Thanks!

**Comment by saghiles** [comment]
Hi, yes you can rely on Cornac to compare various models on your dataset. You can follow the different examples provided in Cornac. That said, not all models would integrate the auxiliary data (texts and images). But you can still compare models regardless of the information they rely on: user x item interactions only, or user x item interactions + some auxiliary data (e.g., item texts).
