### ISSUE TITLE
[ASK] Cornac at scale for 100M users 

### ISSUE THREAD

**Issue by extendfuture** [PreferredAI/cornac#478]
### Description
We are building recommendation system for 100M users. We have ~100 interactions per user. Would like to understand how cornac can be setup on cloud to run BPR and FM at such scale? We extensively used pyspark, aws emr so far and open for sagemaker. Really appreciate any pointers or previous case studies or evaluations. 

Thanks!

**Comment by saghiles** [comment]
Hi, we do not have a previous experience with running Cornac at this scale. Technically it should be possible to scale the models in Cornac to handle that many users. At this time however we are not able to provide support for such scenario. 

We would be more than happy to hear from you regarding your experience trying to scale Cornac to web-scale datasets. 

Thank you!
