### ISSUE TITLE
[ASK] Is BiVAE model theta and beta dimension exchanged unexpectedly?

### ISSUE THREAD

**Issue by yanzijun922** [PreferredAI/cornac#479]
cornac/cornac/models/bivaecf/bivae.py line 49,50
Are user and item latent vector dimensions exchanged unexpected?

self.mu_theta = torch.zeros((item_encoder_structure[0], k))  # n_users*k
self.mu_beta = torch.zeros((user_encoder_structure[0], k))  # n_items*k

It seems already been commented out.
I found this when trying to evaluate the similarity between user/item latent vector

**Comment by saghiles** [comment]
Hi,

Thanks Marta for clarifying this aspect. 

@yanzijun922 please refer to @mmosc's answer.

This issue is solved so I will close it.
