### ISSUE TITLE
[ASK / FEATURE] CVAE architecture

### ISSUE THREAD

**Issue by mmosc** [PreferredAI/cornac#481]
Hi!
Browsing [the implementation of CVAE](https://github.com/PreferredAI/cornac/blob/1e5c9794ee04567597c966f241af7f82113702bb/cornac/models/cvae/cvae.py) and trying out the model, it seems to me that the only allowed architecture is with two layers. (i.e., `layers` *must* be a list with two elements)

Is that right?

If so, I believe that this is a great limitation to the model, which should be generalized to an arbitrary number of `layers`.

Cheers!
Marta

**Comment by saghiles** [comment]
Hi Marta, 

Right current CVAE implementation assumes two layers. As we are dealing with extremely sparse data going beyond that number of layers is unlikely to bring significant improvements.

That said it would great to improve that implementation to accommodate any number of layers. Please feel free to make a PR on that if you wish, your contribution will be more than welcome. 

I will close this issue as it is solved.

Thank you.
