### ISSUE TITLE
[BUG] Incompatibility of `.log` path with some models

### ISSUE THREAD

**Issue by mmosc** [PreferredAI/cornac#482]
Hi!
I am running some experiments with cornac and would like to decide on where to store the `.log` file. Although the path can be set with the `save_dir` parameter, setting a value for this parameter is not possible with all models. The reason is that setting `save_dir` to something that is not `False` automatically implies trying to store the model after training, and not all models can be stored.

See [documentation](https://cornac.readthedocs.io/en/latest/_modules/cornac/experiment/experiment.html): 
> save_dir: str, optional, default: None Path to a directory for storing trained models and logs. If None,  models will NOT be stored and logs will be saved in the current working directory.

Maybe an additional parameter can be added to the `Class Experiment`, to separate the path of the log from the decision of whether to store the model (until all models support storing, which of course would be even nicer :blush:  )

Cheers!
Marta

**Comment by saghiles** [comment]
Hi, thanks for raising this point. It is a good suggestion indeed to be able to specify a separate path for the log dir. Please feel free open a PR on this. Otherwise we'll take this into account in the upcoming versions of Cornac. 
Thank you!

**Comment by mmosc** [comment]
Hi and thanks for your reply!
As a follow up question, since you mentioned it: is there an upcoming new version of cornac planned?

**Comment by saghiles** [comment]
Hi, absolutely, welcome!
There is a new release planed soon, as there are some changes (e.g., new models) since the last release. All these changes are already available if you install Cornac from the source code.
