### ISSUE TITLE
[FEATURE] cornac.datasets.office.load_feedback() is not working

### ISSUE THREAD

**Issue by shezgone** [PreferredAI/cornac#484]
### Description
cornac.datasets.office.load_feedback() is not working
Is there any way to do a workaround?
```python
from cornac.datasets import amazon_office as office
ratings = office.load_feedback()
```

### Expected behavior with the suggested feature

Result:
HTTPError: HTTP Error 502: Bad Gateway

**Comment by saghiles** [comment]
Hi, this is unfortunately due to some issues with the server hosting Cornac datasets. It should be fixed now. In case you are actively working with Cornac, I would recommend downloading the datasets you are interested in to avoid experiencing this issue again.
