### ISSUE TITLE
[BUG] Factorization Machines (FM) fm_example.py crashes

### ISSUE THREAD

**Issue by adebiasio-estilos** [PreferredAI/cornac#486]
Running the example **fm_example.py** for **Factorization Machines (FM)** produces a jupyter notebook crash.

**Comment by saghiles** [comment]
Hi, could you please provide us some more details? On which OS system are you running your code? does this issue happen only when running the FM example from a Jupyter notebook? 

Note: the current FM implementation requires Linux as the OS the system.
