### ISSUE TITLE
[ASK] Experiment Ranking Eval Rating Threshold

### ISSUE THREAD

**Issue by deychak** [PreferredAI/cornac#488]
### Description

Given the following (slightly redacted) experiment, I wanted to confirm how the rating threshold is applied during ranking evaluation when providing my own UIR data via `from_splits`. Reading the implementations, I see that first the model is fit ([here](https://github.com/PreferredAI/cornac/blob/master/cornac/experiment/experiment.py#L131), [here](https://github.com/PreferredAI/cornac/blob/master/cornac/eval_methods/base_method.py#L700)) before ranking eval is [invoked](https://github.com/PreferredAI/cornac/blob/master/cornac/eval_methods/base_method.py#L710), of course. However, it isn't until that ranking eval routine where the rating threshold is [applied](https://github.com/PreferredAI/cornac/blob/master/cornac/eval_methods/base_method.py#L170). If my train, val, and test input data that I pass to `from_splits` has ratings `{1.0, 10.0, 100.0}` this means the model will be trained based on all of those interactions but when evaluated, only the interactions based on the rating threshold will be kept in the test set, in this case, 100.0. Is this correct? In other words, the model is trained on all interactions but evaluated against the subset that are `>= rating_threshold`.

```python
split = cr.eval_methods.BaseMethod.from_splits(
    train_data=trn_intr_cr,
    test_data=tst_intr_cr,
    val_data=val_intr_cr,
    fmt='UIR',
    rating_threshold=100.0,
    exclude_unknowns=False,
    verbose=True,
)

metric = cr.metrics.Recall(k=. . .)

rs = cr_hpt.RandomSearch(
    model=. . .,
    space=[. . .],
    metric=metric,
    eval_method=split,
    n_trails=. . .,
)

cr.Experiment(
  eval_method=split,
  models=[rs],
  metrics=[metric],
  user_based=True,
  verbose=False,
).run()

print(rs.best_params)
```

**Comment by saghiles** [comment]
Hi, yes correct. The model is trained on all rating values, and the threshold is used at test time only to decide if a given item is positive (good recommendation). This relevant for Top-N list recommendation or ranking metrics (e.g., Precision, Recall, NDCG) only.
