### ISSUE TITLE
[BUG] CVAE not training on GPU

### ISSUE THREAD

**Issue by mmosc** [PreferredAI/cornac#490]
### Description
Hi,

Once again, thank you for developing this recommendation library!

I'm training several models (CVAE, VAECF, BiVAECF) on the same dataset, on the same machines,  performing a grid search in some parameter space. While I get some of the models to train on GPU, this is not the case for CVAE.

### In which platform does it happen?
```
(cornac) marta@mymachine:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
### How do we replicate the issue?
My script runs in a venv with python3.6, with the command:
```
(cornac) marta@mymachine:~$ CUDA_VISIBLE_DEVICES=0 python3.6 adapted_training.py
```
The models I train are CVAE, VAECF, BiVAECF, with the very same script. The latter two train on GPU, while CVAE does not. Here are the parameters for CVAE.
```
        # CVAE WITH FEATURES
         'cvae_content': {
             'cornac_model': CVAE,
             'params': {
                'z_dim': [10, 20, 50],
                'vae_layers': [[200, 100], [400, 200]],
                'act_fn': ['sigmoid'],
                'n_epochs': [100],
                'lr': [1.e-2, 1.e-3, 1.e-4],
                'batch_size': [128],
                'lambda_u': [1.e-4],
                'lambda_v': [1.e-3],
                'lambda_r': [10.],
                'lambda_w': [1.e-4],
                'a': [1.],
                'b': [0.01],
                'seed': [cornac_seed],
                'verbose': [True],
            },
            'features': {
                'vgg':  FEATURES_FOLDER + 'id_vgg19.tsv',
            },
            'eval_method_params': {
                'item_feature': None,
                'item_text': True,
            },
         },}
```

Any suggestions about how to let CVAE train on GPU? 

Best, 
Marta

**Comment by saghiles** [comment]
Hi, the current CVAE implementation in Cornac does not support GPU training. You can improve that by following the BiVAECF code to support GPU training for CVAE. If you do so, please feel free to open PR. I am closing this issue, in case there are any related questions/issues, please reopen it :). 
Thank you!
