### ISSUE TITLE
[ASK] pip install doesn't include updated version

### ISSUE THREAD

**Issue by amil-khare** [PreferredAI/cornac#491]
### `pip install cornac` doesn't include updated version

I planned to use EASE model for basic recommendations task. I installed the package via pip.
`from cornac.models import EASE`
`cannot import name 'EASE' from 'cornac.models'`

### Other Comments
Python Version - 3.8
Cornac Version - 1.14.2

**Comment by saghiles** [comment]
Hi thanks for raising this. We did not yet release a new version of Cornac since EASE has been added. We are planning a new release soon. In the mean time please install Cornac from source to have access to EASE. 
Thank you!
