### ISSUE TITLE
[BUG] HTTP 502 error when downloading a dataset from static.preferred.ai

### ISSUE THREAD

**Issue by mrticker** [PreferredAI/cornac#492]
CVAE example fails with

```
C:\usr\Miniconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 502: Bad Gateway
```

This is also visible in a browser:
https://static.preferred.ai/cornac/datasets/citeulike/text.zip

**Comment by saghiles** [comment]
Hi, there were some issues with the server hosting cornac datasets. I was able to download the citeulike dataset, so I guess it should be working fine now. Please let us know if the issue persists.
