### ISSUE TITLE
BiVAE: why is num_items assigned user_encoder_structure and num_users assigned item_encoder_structure? 

### ISSUE THREAD

**Issue by johanneskruse** [PreferredAI/cornac#493]
### Description
I was wondering about the following, `num_items` is set to `user_encoder_structure` and  `num_users` is set to `item_encoder_structure` . 

```
                self.bivae = BiVAE(
                    k=self.k,
                    user_encoder_structure=[num_items] + self.encoder_structure,
                    item_encoder_structure=[num_users] + self.encoder_structure,
                    act_fn=self.act_fn,
                    likelihood=self.likelihood,
                    cap_priors=self.cap_priors,
                    feature_dim=feature_dim,
                    batch_size=self.batch_size,
                ).to(self.device)
```

Which is then assigned the following:  

```
class BiVAE(nn.Module):
    def __init__(
        self,
        k,
        user_encoder_structure,
        item_encoder_structure,
        act_fn,
        likelihood,
        cap_priors,
        feature_dim,
        batch_size,
    ):
        super(BiVAE, self).__init__()

        self.mu_theta = torch.zeros((item_encoder_structure[0], k))  # n_users*k
        self.mu_beta = torch.zeros((user_encoder_structure[0], k))  # n_items*k
(...)
```

Is there a specific motivation for this? I can see it is just about the `mu_theta` and `mu_beta`, hence just calling them correct but for readability I am a bit confused. 

### Other Comments
Link: 
- https://github.com/PreferredAI/cornac/blob/master/cornac/models/bivaecf/bivae.py
- https://github.com/PreferredAI/cornac/blob/master/cornac/models/bivaecf/recom_bivaecf.py

**Comment by saghiles** [comment]
Hi, it's for the same raisons as explained in the following solved [issue](https://github.com/PreferredAI/cornac/issues/479). 
I am closing this issue. Please feel free to reopen it if there any other related questions. 
Thank you!
