### ISSUE TITLE
GNU library compatibility issues

### ISSUE THREAD

**Issue by SavvinaDaniil** [PreferredAI/cornac#494]
### Description
Dear cornac developers,

I am trying to use cornac within the server of my university. However, I get a compatibility issue when I import; cornac requires GNU libc version of 2.27, and ours is 2.25. 

I wonder if you can suggest any work around. E.g., is there an older cornac version that requires an earlier version of libc?

Thank you in advance!

**Comment by tqtg** [comment]
I would suggest to use Python 3.8-3.11 and use the pre-built files to install, either using `pip` or `conda`.
