### ISSUE TITLE
Why are the examples not running? Problem with import of cornac

### ISSUE THREAD

**Issue by yvonnerahnfeld** [PreferredAI/cornac#496]
I just installed cornac from github, liked described in the readme file. But now if I try to execute one of the examples, I always get the error:
ModuleNotFoundError: No module named 'cornac.utils.fast_sparse_funcs'
why does the import of cornac fail if everything is installed? On Colab within a Jupyter Notebook everything works fine, except the WMF model, because of a deprecated method. Because of this bug I`d like to use cornac on my laptop instead of running it from Colab, to fix this bug.

**Comment by tqtg** [comment]
Related issues: https://github.com/PreferredAI/cornac/issues/396, https://github.com/PreferredAI/cornac/issues/296
