### ISSUE TITLE
Use of deprecated tensorflow method

### ISSUE THREAD

**Issue by yvonnerahnfeld** [PreferredAI/cornac#497]
### Description
The WMF model cannot be used in Experiment, due to a depricated tensorflow method. The new method must be 'tf.random.set_seed()'. The error output is like:

[/usr/local/lib/python3.8/dist-packages/cornac/models/wmf/recom_wmf.py](https://localhost:8080/#) in _fit_cf(self)
    165         graph = tf.Graph()
    166         with graph.as_default():
--> 167             tf.set_random_seed(self.seed)
    168             model = Model(
    169                 n_users=n_users,

AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

### In which platform does it happen?
Found while using in google colab.

### How do we replicate the issue?
Try to use the WMF model in an Experiment

### solution
In line 167 of recom_wmf.py change 'tf.set_random_seed()' to 'tf.random.set_seed()'.

**Comment by tqtg** [comment]
Related issue: https://github.com/PreferredAI/cornac/issues/495
