### ISSUE TITLE
Module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by CleverShovel** [PreferredAI/cornac#498]
### Description

AttributeError: module 'numpy' has no attribute 'int' in this code
`train_val = Dataset.build(train[['user_id', 'item_id', 'timespent']].values, seed=SEED)`
Stacktrace leads to this line https://github.com/PreferredAI/cornac/blob/master/cornac/data/dataset.py#L367
### In which platform does it happen?
numpy==1.24.1

### Other Comments
Attribute numpy.int is deprecated since 1.20 and removed in 1.24. So downgrading numpy to 1.22.0 works fine in my case.

**Comment by AndreasKarasenko** [comment]
Technically downgrading to 1.23.0 is sufficient.
I think the setup.py should be adjusted accordingly:
"Please install numpy>=1.14, <1.24.0 first."

Adjusting for numpy==1.24.0 should work if you change np.int to np.int_
Then again Visual Studio 2015 is depreceated for this release.

**Comment by tqtg** [comment]
Solved with version 1.15.0
