### ISSUE TITLE
[BUG] ValueError: invalid literal for int() with base 10: '2018-01-02'

### ISSUE THREAD

**Issue by AndreasKarasenko** [PreferredAI/cornac#500]
### Description
Trying to use the UIRT format in datasets.load_feedback and Reader.read leads to a ValueError.
The Stacktrace leads to the [uirt_parser](https://github.com/PreferredAI/cornac/blob/93058c04a15348de60b5190bda90a82dafa9d8b6/cornac/data/reader.py#L35-L36).

From the cached dataset it looks like uirt_parser tries the following:
`return [(tokens[0], tokens[1], float(tokens[2]), int(tokens[3]))]`
Where tokens[3] accesses the timestamp which has a string format of 'yyyy-mm-dd'.
For example: `int('2018-01-02')`

### In which platform does it happen?
I encountered this problem under Python 3.10.9 on a Windows 10 machine for a private dataset and the netflix dataset.

### How do we replicate the issue?
Run the [Netflix BPR example](https://github.com/PreferredAI/cornac/blob/master/examples/bpr_netflix.py) but change line 24 to:
`feedback = netflix.load_feedback(fmt="UIRT", variant="small", reader=Reader(bin_threshold=1.0))`

### Expected behavior (i.e. solution)
Unsure, I don't know how the timestamps should be represented.

**Comment by tqtg** [comment]
This is due to the format of the Netflix dataset where the timestamp is not a number but a date string. We might need to convert the time column into a number first.
