### ISSUE TITLE
[ASK] Issue with computing similarity for KNN

### ISSUE THREAD

**Issue by SavvinaDaniil** [PreferredAI/cornac#501]
### Description

Hi! I have been using Cornac for a while now. Recently I switched to a different library and very soon realized that for the same train-test split, as well as hyperparameters, UserKNN and ItemKNN made completely different predictions between the two libraries. 

I couldn't figure out why, so I hard coded calculating the similarity matrixes and saw that Cornac was producing a different similarity matrix than the one I was calculating. 

Diving into the Cornac source code, I managed to find the reasong why:

I found the reason in the module cornac.models.knn.similarity.compute_similarity. Basically, you consider when averaging  **only the items for which both users have given rating**. In other words, if two users have rated 1000 items each but only have rated **one** item in common, but they gave it the same rating, then their cosine similarity will be **1**! 

I was wondering if this choice is deliberate and whether you have thoughts on what makes more sense.

Thanks!

**Comment by tqtg** [comment]
Thanks for diving deep into the difference. We acknowledge that there are multiple variants in the implementation of the kNN method for recommender systems. Each variant has its own motivation and interpretation. In Cornac, we follow the one described in [Recommender Systems: The Textbook by Charu Aggarwal](http://pzs.dstu.dp.ua/DataMining/recom/bibl/1aggarwal_c_c_recommender_systems_the_textbook.pdf). You could refer to Section 2.3.1 for the explanation. In addition, we have a [tutorial](https://github.com/PreferredAI/tutorials/blob/master/recommender-systems/02_neighborhood.ipynb) on this neighborhood-based topic that's supplemented with the code.
