### ISSUE TITLE
[ASK] Mean centering in KNN models.

### ISSUE THREAD

**Issue by SavvinaDaniil** [PreferredAI/cornac#502]
### Description

Hi! I noticed something in the KNN implementations that I am curious about. Both ItemKNN and UserKNN allow the user to set mean_centered to True or False.

However, I noticed that when setting mean_centered to False, while the similarities are calculated over the non-mean centered ratings, the predicted score is still calculated over the mean centered ratings. See the fit method: 

```
if self.train_set.min_rating != self.train_set.max_rating:  # explicit feedback
            self.ui_mat, self.mean_arr = _mean_centered(self.ui_mat)

if self.mean_centered:
            weight_mat = self.ui_mat.copy()
else:
            weight_mat = self.train_set.matrix.copy()
```

In the score method, ui_mat is used, which is already mean centered, regardless of whether the user chose True or False when instantiating the model.

**Comment by tqtg** [comment]
`mean_centered` is for the usage of computing weighting matrix, in turns computing similarity. For the final rating prediction, we always add back the mean rating of a particular user to scale back to the original rating scale. Please refer to the return statement in the score function.
