### ISSUE TITLE
Changing EASE parameters

### ISSUE THREAD

**Issue by jyyang621** [PreferredAI/cornac#513]
When I want to tune EASE model, I change the `lamb` parameter: `ease = EASE(lamb = 0.1)`
But it gives me this error always:
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
Cell In[19], line 1
----> 1 cornac.Experiment(eval_method = eval_method, models = [ease], metrics = eval_metrics).run()

File D:\Anaconda3\lib\site-packages\cornac\experiment\experiment.py:156, in Experiment.run(self)
    154 output_file = os.path.join(save_dir, "CornacExp-{}.log".format(timestamp))
    155 with open(output_file, "w") as f:
--> 156     f.write(output)

UnicodeEncodeError: 'gbk' codec can't encode character '\u1d3f' in position 210: illegal multibyte sequence

**Comment by tqtg** [comment]
I guess the name `EASEᴿ (B>-∞)` having some special unicode characters that can't be encoded and written down on file in your env. Maybe you can try to simplify the name to `EASE` and see if it works.
