### ISSUE TITLE
[FEATURE]NEW DATA

### ISSUE THREAD

**Issue by MountainShan214** [PreferredAI/cornac#572]
Hello, thank you very much for providing such a friendly framework for everyone. How can new data be added to model training?

**Comment by lthoang** [comment]
I would suggest to use `cornac.data.Reader`. You can use `read` method to load your data under predefined format, e.g., `UIR` for (user, item, rating) tuples or `UIRT` for (user, item, rating, timestamp) tuples.

Specifically, if your data in stored in csv file with `UIR` format. Content in `file_path`:
```
u1,i1,r1
u2,i2,r2
...
```

You can use the following snippet:

```python
from cornac.data import Reader

reader = Reader()
data = reader.read(file_path, fmt="UIR", sep=",")
# data will be a list of tuples [(u1, i1, r1), u1, i1, r2), ...]
...
```
