### ISSUE TITLE
[DOCS] Couldn't find documentation on TIFUKNN

### ISSUE THREAD

**Issue by samruddha-kf** [PreferredAI/cornac#576]
### Description
In API reference I couldn't find information about model TIFUKNN, although in git repo it is available.

**Comment by lthoang** [comment]
https://cornac.readthedocs.io/en/latest/api_ref/models.html#module-cornac.models.tifuknn.recom_tifuknn

**Comment by samruddha-kf** [comment]
> https://cornac.readthedocs.io/en/latest/api_ref/models.html#module-cornac.models.tifuknn.recom_tifuknn

thanks

**Comment by samruddha-kf** [comment]
Thanks!

**Comment by tqtg** [comment]
@darrylong this is why we might want to point users to our latest docs

**Comment by darrylong** [comment]
@tqtg yes, but initially was assuming that users generally don't install Cornac by source. I'm okay if we switch it to latest.
