### ISSUE TITLE
[ASK] How should be the data format for basket task, UBIT/UBITJson?

### ISSUE THREAD

**Issue by samruddha-kf** [PreferredAI/cornac#577]
### Description
I am trying to use TIFUKNN algorithm for developing recommender. And I was trying to build a dataset for that. While I created a csv with user, basketid, items (list separated by ' '(space)) and timestamp columns. It is throwing an error. So how should I design a item column, i.e. list of items? Is specific separator need to be used for item list?

Another general question I have is -
If I have other interaction specific features such as holiday, weekend, location. Should I include those in json as key:value pair? If so which models support utilizing such kind of information?
Thanks!

**Comment by lthoang** [comment]
About data formatting, the default supported format separator is `sep="\t"` using the method read inside `Reader` class. Example of usage as follow, 
```python
reader  = cornac.data.Reader()
reader.read(file_path, fmt="UBIT", sep="\t")
```
I suggest you to transform your data using `"\t"` as separator. If you are using other separator, you can just specify it via `sep` argument.

For extra information that you want to incorporate into your dataset. You can include those in json format. For example, [tafeng dataset](https://github.com/PreferredAI/cornac/blob/master/cornac/datasets/tafeng.py) use `UBITJson` format, the extra data including price and quantity, e.g., `{"quantity": 2, "price": 10.0}`.

If you are looking for example of usage, please take a look at `GPTop` model implementation at https://github.com/PreferredAI/cornac/blob/master/cornac/models/gp_top/recom_gp_top.py. This model have an option to use `quantity` information included in `extra_data`.
