### ISSUE TITLE
[FEATURE] There is no model type in table models

### ISSUE THREAD

**Issue by lthoang** [PreferredAI/cornac#585]
### Description

Currently, we list all models in https://github.com/PreferredAI/cornac#models, including general recommendation models, next-item recommendation models, and next-basket recommendation models. Without any clarification, it is difficult to know which model belong to which type of recommender.

### Expected behavior with the suggested feature
To leverage the navigation, I suggest two options:

1. Add column model type in https://github.com/PreferredAI/cornac#models to indicate the type of recommender
2. Split table models into different tables, each list a type of recommender

@darrylong @tqtg @hieuddo Any suggestion?

**Comment by tqtg** [comment]
Agree. I was thinking to add a column after we have a good categorization of models, rearrange the models folder. For now, let’s keep adding new models to the current collection. We will come to this eventually.

**Comment by tqtg** [comment]
Now thinking about this, I consider it to be an easier exercise to start with. We can create a column `Model Type` to specify the category/family of the models, then we can rearrange the models folder after we're happy with this. Would you mind create a PR for this and others can contribute? @lthoang
