### ISSUE TITLE
[BUG] Trirank documentation X&Y

### ISSUE THREAD

**Issue by linan1109** [PreferredAI/cornac#618]
For model.Triank, the document says X is for user-aspect and Y is for item-aspect. 

But in the code, it should be the other way round, i.e. X for item-aspect and Y for user-aspect. 

![image](https://github.com/PreferredAI/cornac/assets/40530883/0676214c-f3d2-480d-837e-39013e692c68)

![image](https://github.com/PreferredAI/cornac/assets/40530883/4e33898b-5294-4380-ac0a-858c1755adfa)

**Comment by tqtg** [comment]
@lthoang is it something to be corrected?

**Comment by lthoang** [comment]
Based on the original paper, the code is correct. I made a mistake in the model's documentation.
<img width="420" alt="image" src="https://github.com/PreferredAI/cornac/assets/2834268/a7a28081-ec4e-48d2-8a5c-7a6eb9bd53c8">

So we have to update the documentation accordingly.

@linan1109 Thank you for pointing out this error.
