### ISSUE TITLE
[BUG] Add amazon_digital_music to datasets init

### ISSUE THREAD

**Issue by pablo-pnunez** [PreferredAI/cornac#620]
### Description

Despite being implemented in `cornac/datasets/amazon_digital_music.py` the file is not listed in `cornac/datasets/__init__.py`.

### In which platform does it happen?

All

### How do we replicate the issue?

```python
dataset = cornac.datasets.amazon_digital_music.load_feedback()
```

### Expected behavior (i.e. solution)

 `cornac/datasets/__init__.py`:
```python
from . import amazon_digital_music
```

**Comment by tqtg** [comment]
@pablo-pnunez thanks for pointing this out. Great catch!

@lthoang looks like we've missed the import statement
