### ISSUE TITLE
[BUG] Crash when using cornac with Numpy 2.0

### ISSUE THREAD

**Issue by quentinhaenn** [PreferredAI/cornac#628]
### Description
Cornac cannot work with Numpy 2.0. Error message: 
"A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'."

### In which platform does it happen?
MacBook with ARM platform (M1)
MacOS 14.5
Python 3.12

### How do we replicate the issue?
Simply install cornac using `pip install cornac` and having numpy 2.0.0, then run:
`from cornac.data import Reader, Dataset`

Rollback to numpy 1.26 solve the issue.

### Expected behavior (i.e. solution)

Expected cornac to run with the new major version of Numpy.

**Comment by tqtg** [comment]
Thanks for reporting the issue. We're currently working towards making Cornac compatible with Numpy 2.0. In the meantime, we can rollback to Numpy 1.xx as you've suggested.

**Comment by quentinhaenn** [comment]
Thanks for the quick reply. I suggest pointing it out in installation process and in pyproject.toml or setup.py depending on which one you're using (with dependencies reporting `numpy<=1.26`until you make the proper migration to Numpy 2.0

Thank again !

**Comment by tqtg** [comment]
We're working on that and it'll be fixed soon in #627

**Comment by darrylong** [comment]
This has been fixed with the release of [Cornac 2.2.2](https://github.com/PreferredAI/cornac/releases/tag/v2.2.2).
