### ISSUE TITLE
[BUG] np.Inf does not supported in numpy>=2.0 cause error in Recommender class reset_info method 

### ISSUE THREAD

**Issue by lthoang** [PreferredAI/cornac#644]
### Description

Using python 3.10, the current numpy version after setting up the environment is numpy=2.1.1. When I run an example experiment, it shown the following error.
<img width="910" alt="image" src="https://github.com/user-attachments/assets/bcb4ec75-911c-4300-ae2c-8a8a48ef28f9">

**Comment by tqtg** [comment]
We have already pin version of Numpy<2.0.0 -- https://github.com/PreferredAI/cornac/blob/73123c95570f1c12bad3ed2ece4a33ff32cb5717/setup.py#L346. With that said, we should probably fix all of compatibility issues when our bandwidth allows.

**Comment by lthoang** [comment]
I think we should also consider to update the following line of code.

https://github.com/PreferredAI/cornac/blob/73123c95570f1c12bad3ed2ece4a33ff32cb5717/setup.py#L40

When I set up a new environment, I often copy the suggestion command to install the missing libraries. Which leads to the issue of installing numpy with a newer version.

**Comment by tqtg** [comment]
Great spot! We should’ve done that as well
